### ISSUE TITLE
the 3-D input to Denselayer

### ISSUE THREAD

**Issue by danlutan** [zsdonghao/tensorlayer#101]
There are some sentence . Shape is [ batch_size , length ,dim ] . ' length' means  the number of words in every sentence . ' dim ' means dimension . Now , I need to put [ batch_size , length , dim ] into a DenseLayer . And then I need to get the output [ batch_size  , length , dim_new ] , 'dim_new' means the n_units of denselayer . Like batch processing , How can I implement it ? (Like TimeDistributed in Keras)

**Comment by zsdonghao** [comment]
@danlutan I think you can do this:

```
x = tf.placeholder('float32', [batch_size, length, dim], name = 'input')
net = InputLayer(x, name='input')
net = Flatten(net, name='flatten')
net = DenseLayer(net, dim_new, name='dense')
net = Reshape(net,  [batch_size , length , dim_new], name='reshape')
```

**Comment by danlutan** [comment]
For example , the shape is [ 5,6,8 ] .When I use Flatten , it become [ 5 , 48 ] ,and the use denselayer which dim_new is 4 .It become [ 5 , 4 ] . It's failed to reshape [5 ,6 ,4] . Moreover , I need to  map the dim of every  length to dim_new ，not to map length*dim to dim_new

**Comment by zsdonghao** [comment]
@danlutan i see, let me think and get back to you shortly, i think there should be some ways without using special layer. if special layer is necessary, i will create one.

thanks

**Comment by zsdonghao** [comment]
@danlutan Hi, thank you for your advice. 

I release a [TimeDistributedLayer](http://tensorlayer.readthedocs.io/en/latest/modules/layers.html#time-distributed-layer) in the master version, please have a try~

**Comment by yoobright** [comment]
I think this implementation build timestep different layer_class in TimeDistributedLayer.

**Comment by zsdonghao** [comment]
@danlutan yeah, I considered parameter sharing. https://github.com/zsdonghao/tensorlayer/blob/master/tensorlayer/layers.py#L2910

here is how I apply a dense layer on every step:
```
batch_size = 32
timestep = 20
input_dim = 100
x = tf.placeholder(dtype=tf.float32, shape=[batch_size, timestep,  input_dim], name="encode_seqs")
net = InputLayer(x, name='input')
net = TimeDistributedLayer(net, layer_class=DenseLayer, args={'n_units':50, 'name':'dense'}, name='time_dense')

print(net.outputs._shape)
net.print_params(False)
```

feel free to let me know if you have problem.

**Comment by yoobright** [comment]
Oh I see, I used to think `name=args['name']+str(i))` as layer_class parameter.

**Comment by zsdonghao** [comment]
Automatically closing due to lack of recent activity. Please reopen when additional information becomes available. Thanks!
