### ISSUE TITLE
Typo in layers.py, line 4527

### ISSUE THREAD

**Issue by geometrikal** [zsdonghao/tensorlayer#102]
Inside the PreluLayer class:

    self.outputs = tf.nn.relu(self.inputs) + tf.mulitply(alphas, (self.inputs - tf.abs(self.inputs))) * 0.5

`multiply` is spelt wrongly, causing an exception.

**Comment by zsdonghao** [comment]
@geometrikal thanks, just fix it in master version

**Comment by geometrikal** [comment]
Cheers. (Great library, have switched to it)
