### ISSUE TITLE
DynamicRNNLayer cannot use GRUCell

### ISSUE THREAD

**Issue by bcy** [zsdonghao/tensorlayer#105]
When set cell_fn = tf.contrib.rnn.GRUCell, DynamicRNNLayer will complain TypeError: __init__() got an unexpected keyword argument 'state_is_tuple'.

Then I read the source code, and find that __init__() calls cell_fn(num_units=n_hidden, **cell_init_args) with the cell_init_args = {'state_is_tuple' : True} set.
In BasicRNNCell, BasicLSTMCell and LSTMCell, this is good, because they all have this parameter. However, GRUCell does not have it. And according to the Tensorflow docs, the 'state_is_tuple' parameter is True by default, so I think it's unnecessary to have it in the cell_init_args.

Do I get the right idea? Or the GRUCell is not suitable for Dynamic RNN by design?

**Comment by zsdonghao** [comment]
@bcy you are right

**Comment by bcy** [comment]
I see that you have committed to master branch. I just pulled and tested, and it works now. Thanks.
