### ISSUE TITLE
tl.utils.fit    TypeError: Fetch argument <tensorflow.python.training.momentum.MomentumOptimizer object at 0x7f0c7d390d50> has invalid type <class 'tensorflow.python.training.momentum.MomentumOptimizer'>, must be a string or Tensor. (Can not convert a MomentumOptimizer into a Tensor or Operation.)

### ISSUE THREAD

**Issue by gjjustc** [zsdonghao/tensorlayer#108]
When  I use tensorlayer to train my data,I write 
######
"tl.utils.fit(sess, network, train_op, cost, x_train, y_train, x, y_,
             acc=acc, batch_size=50, n_epoch=20, print_freq=2,
             X_val=x_test, y_val=y_test, eval_train=False)" 

However,it tells me that:

####
Start training the network ...
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-20-9cb9b6053600> in <module>()
      1 tl.utils.fit(sess, network, train_op, cost, x_train, y_train, x, y_,
      2              acc=acc, batch_size=50, n_epoch=20, print_freq=2,
----> 3              X_val=x_test, y_val=y_test, eval_train=False)

/home/gjj/anaconda2/lib/python2.7/site-packages/tensorlayer/utils.pyc in fit(sess, network, train_op, cost, X_train, y_train, x, y_, acc, batch_size, n_epoch, print_freq, X_val, y_val, eval_train, tensorboard, tensorboard_epoch_freq, tensorboard_weight_histograms, tensorboard_graph_vis)
    114             feed_dict = {x: X_train_a, y_: y_train_a}
    115             feed_dict.update( network.all_drop )    # enable noise layers
--> 116             loss, _ = sess.run([cost, train_op], feed_dict=feed_dict)
    117             loss_ep += loss
    118             n_step += 1

/home/gjj/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in run(self, fetches, feed_dict, options, run_metadata)
    765     try:
    766       result = self._run(None, fetches, feed_dict, options_ptr,
--> 767                          run_metadata_ptr)
    768       if run_metadata:
    769         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

/home/gjj/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in _run(self, handle, fetches, feed_dict, options, run_metadata)
    950 
    951     # Create a fetch handler to take care of the structure of fetches.
--> 952     fetch_handler = _FetchHandler(self._graph, fetches, feed_dict_string)
    953 
    954     # Run request and get response.

/home/gjj/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in __init__(self, graph, fetches, feeds)
    406     """
    407     with graph.as_default():
--> 408       self._fetch_mapper = _FetchMapper.for_fetch(fetches)
    409     self._fetches = []
    410     self._targets = []

/home/gjj/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in for_fetch(fetch)
    228     elif isinstance(fetch, (list, tuple)):
    229       # NOTE(touts): This is also the code path for namedtuples.
--> 230       return _ListFetchMapper(fetch)
    231     elif isinstance(fetch, dict):
    232       return _DictFetchMapper(fetch)

/home/gjj/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in __init__(self, fetches)
    335     """
    336     self._fetch_type = type(fetches)
--> 337     self._mappers = [_FetchMapper.for_fetch(fetch) for fetch in fetches]
    338     self._unique_fetches, self._value_indices = _uniquify_fetches(self._mappers)
    339 

/home/gjj/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in for_fetch(fetch)
    236         if isinstance(fetch, tensor_type):
    237           fetches, contraction_fn = fetch_fn(fetch)
--> 238           return _ElementFetchMapper(fetches, contraction_fn)
    239     # Did not find anything.
    240     raise TypeError('Fetch argument %r has invalid type %r' %

/home/gjj/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in __init__(self, fetches, contraction_fn)
    269         raise TypeError('Fetch argument %r has invalid type %r, '
    270                         'must be a string or Tensor. (%s)'
--> 271                         % (fetch, type(fetch), str(e)))
    272       except ValueError as e:
    273         raise ValueError('Fetch argument %r cannot be interpreted as a '

TypeError: Fetch argument <tensorflow.python.training.momentum.MomentumOptimizer object at 0x7f0c7d390d50> has invalid type <class 'tensorflow.python.training.momentum.MomentumOptimizer'>, must be a string or Tensor. (Can not convert a MomentumOptimizer into a Tensor or Operation.)

I am so puzzled about where the problem is。Can you help me ? Thank you very much.

**Comment by boscotsang** [comment]
Could you show us the definition of network, train_op, x and y_?

**Comment by gjjustc** [comment]
#define network
    sess = tf.InteractiveSession()
    
    x = tf.placeholder(tf.float32,shape= [None,227,227,1],name= 'x')
    y_ = tf.placeholder(tf.float32,shape= [None,],name= 'y_')
   
    w_init = tf.truncated_normal_initializer(stddev=0.01)
    b_init = tf.constant_initializer(value=0.0)

    network = tl.layers.InputLayer(inputs = x,n_features=1)                 #227*227
    #1
    network = tl.layers.Conv2d(network,32,(9,9),(2,2),act = tf.nn.relu,padding='VALID',
                        W_init=w_init, b_init=b_init, name='conv1')                 #110*110
    network = tl.layers.MeanPool2d(network,(2,2),padding ='VALID',name = 'pool1')   #55*55
    #2
    network = tl.layers.Conv2d(network,64,(7,7),(1,1),act = tf.nn.relu,padding='VALID',   #49*49
                        W_init=w_init, b_init=b_init, name='conv2')
    network = tl.layers.MeanPool2d(network,(2,2),padding ='VALID',name = 'pool2')    #24*24
    #3
    network = tl.layers.Conv2d(network,128,(5,5),(1,1),act = tf.nn.relu,padding='VALID',   #20*20
                        W_init=w_init, b_init=b_init, name='conv3')
    network = tl.layers.MeanPool2d(network,(2,2),padding ='VALID',name = 'pool3')    #10*10
    #4
    network = tl.layers.Conv2d(network,128,(3,3),(1,1),act = tf.nn.relu,padding='VALID',
                        W_init=w_init, b_init=b_init, name='conv4')                  #8*8
    network = tl.layers.MeanPool2d(network,(1,1),padding ='SAME',name = 'pool4')     #4*4
    #flatten layer
    network = tl.layers.FlattenLayer(network, name='flatten_layer')
    #fully connected
    network = tl.layers.DenseLayer(network,n_units=500,act=tf.nn.relu,W_init=w_init,name='relu_layer1')
    network = tl.layers.DenseLayer(network,n_units=100,act=tf.nn.relu,W_init=w_init,name='relu_layer2')
    network = tl.layers.DenseLayer(network,n_units=1,act=tf.nn.relu,W_init=w_init,name='out_layer')
    
    y = network.outputs
    cost =tl.cost.mean_squared_error(y, y_)
    acc = tf.reduce_mean(abs(y-y_))
    y_op = y
    
    train_params = network.all_params
    
    #train_op = tf.train.MomentumOptimizer(learning_rate=0.001, momentum=0.99)
    mse = tf.reduce_mean(tf.square(y - y_))
    train_op = tf.train.GradientDescentOptimizer(0.3).minimize(mse)
    
    sess.run(tf.global_variables_initializer())
    
    network.print_params()
    network.print_layers()
    
    sess.run(train_op,feed_dict={x: x_train, y_: y_train})

**Comment by boscotsang** [comment]
It seems that the statement you comment `train_op = tf.train.MomentumOptimizer(learning_rate=0.001, momentum=0.99)` before pass a MomentumOptimizer instance instead of an operation to the tl.utils.fit.

**Comment by gjjustc** [comment]
OK,Thank you. I'll have a try.
