### ISSUE TITLE
Could it works in tensorflow Estimator?

### ISSUE THREAD

**Issue by luopuya** [zsdonghao/tensorlayer#113]
estimator accepts "model_fn" that described the model

for examle (DNNRegressor)
```Python
def dnn_regressor_fn(features, targets, mode, params):
    fc1 = layers.relu(features, 10)
    fc2 = layers.relu(fc1, 10)
    predictions = tf.reshape(layers.linear(fc2, 1), [-1])
    # ...
```

could it be replace like
```Python
from tensorlayer import layers as tll
l = tll.InputLayer(...)
l = tll.DenseLayer(...)
l = tll.DenseLayer(...)
l = tll.ReshapeLayer(...)
predictions = l.outputs
```

**Comment by zsdonghao** [comment]
Yes, i think you can use this function [click](http://tensorlayer.readthedocs.io/en/latest/modules/layers.html#connect-keras)
, [example](https://github.com/zsdonghao/tensorlayer/blob/master/example/tutorial_keras.py)

**Comment by luopuya** [comment]
Thanks for replying~

The example use model_fn to create tensorlayer's Layer. 
Could it use in the opposite way? 
I would like to construct model_fn with Layers. (use Layers inside the model_fn)
In this way I could generate the an tensorflow.contrib.learn.Estimator instance.

The reason I choose the Estimator is that it works as sklearn's Estimator (fit and evaluate), and it can be use it sklearn's Pipeline. Moreover, it accepts monitors to record and control the processing. So I think it may be easier to fine-tune the parameters.

I'm a beginner tensorflow and tensorlayer, I wonder if there is a more automatic way (or pipeline as grid search) to fine-tune the parameters?

**Comment by luopuya** [comment]
If I simply replace the code to use tensorlayer's Layers, it may cause problem about variable's name. 
In fit, evaluate and predict, the model_fn would be called, construct the graph and load the trained parameters. 
So maybe it should be used outside the model_fn? 

An model_fn example: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/tutorials/estimators/abalone.py

**Comment by luopuya** [comment]
it seems that adding "tl.layers.set_name_reuse(True)" works

**Comment by zsdonghao** [comment]
i think the problem have been solved?
