### ISSUE TITLE
Lambda Layer Availability

### ISSUE THREAD

**Issue by ritchieng** [zsdonghao/tensorlayer#13]
Is there an equivalent of a [Lambda layer](https://keras.io/layers/core/#lambda) (from Keras) for TensorLayer?

**Comment by zsdonghao** [comment]
Hi, we didn't have lambda layer, but I just created one which is able to use the provided function.

Let me know if it helps.

```
import tensorflow as tf
import tensorlayer as tl

Layer = tl.layers.Layer

class LambdaLayer(Layer):
    """
    """
    def __init__(
        self,
        layer = None,
        fn = None,
        name = 'lambda_layer',
    ):
        Layer.__init__(self, name=name)
        self.inputs = layer.outputs

        print("  tensorlayer:Instantiate LambdaLayer  %s" % self.name)
        with tf.variable_scope(name) as vs:
            self.outputs = fn(self.inputs)

        self.all_layers = list(layer.all_layers)
        self.all_params = list(layer.all_params)
        self.all_drop = dict(layer.all_drop)
        self.all_layers.extend( [self.outputs] )
```

**Comment by ritchieng** [comment]
@zsdonghao Thanks, you're really helpful! I'll try this once I get a fix on your merge layer. I was stuck with this and another issue with your merge layer on building an open-source Wide ResNet.

For your merge layer, Keras has an option for [sum](https://keras.io/layers/core/#merge).

This is an abstract of the code if you dig into it on what sum does:
```
if self.mode == 'sum' or self.mode == 'ave':
            s = inputs[0]
            for i in range(1, len(inputs)):
                s += inputs[i]
            if self.mode == 'ave':
                s /= len(inputs)
            return s

        elif self.mode == 'concat':
            return K.concatenate(inputs, axis=self.concat_axis)
```

This is a [working Keras version](https://gist.github.com/ritchieng/019fc573a3024b42a76432ceb94e63f5) I created and tested for Wide ResNet. Wide ResNet is a CNN that outperforms Deep ResNets with fewer layers (a lot fewer). 

I'm trying to map it over to TensorLayer to show the flexibility of TensorLayer in building more complex systems. Writing a [guide](http://www.ritchieng.com/) and will attribute your help. 

Thanks for supporting again.

**Comment by ritchieng** [comment]
@zsdonghao There's a need for `arguments: optional dictionary of keyword arguments to be passed to the function.`

What do you recommend? Is this how it would work?

```
import tensorflow as tf
import tensorlayer as tl

Layer = tl.layers.LambdaLayer(x, function_name, arguments={'pad': nb_filters - prev_nb_channels})

class LambdaLayer(Layer):
    """
    """
    def __init__(
        self,
        layer = None,
        fn = None,
        arguments = None,
        name = 'lambda_layer',
    ):
        Layer.__init__(self, name=name)
        self.inputs = layer.outputs

        print("  tensorlayer:Instantiate LambdaLayer  %s" % self.name)
        with tf.variable_scope(name) as vs:
            self.outputs = fn(self.inputs, **arguments)

        self.all_layers = list(layer.all_layers)
        self.all_params = list(layer.all_params)
        self.all_drop = dict(layer.all_drop)
        self.all_layers.extend( [self.outputs] )
```

**Comment by wagamamaz** [comment]
If you read the source code, it is obvious.
```
'Conv2dLayer' object has no attribute 'get_shape'
```
you can get the shape of input and output by ``network.inputs.get_shape()`` or ``network.outputs.get_shape()``

**Comment by ritchieng** [comment]
@wagamamaz Thanks.
