### ISSUE TITLE
Suggestion: Consider rename deconv layers to ConvNDTranspose?

### ISSUE THREAD

**Issue by wangg12** [zsdonghao/tensorlayer#136]
Keras and TF both have this name convention and actually deconv layers may mislead people since this is not real deconv. See [https://github.com/fchollet/keras/issues/3502](https://github.com/fchollet/keras/issues/3502).

**Comment by zsdonghao** [comment]
@wangg12 thanks for your advice. 
actually i knew this when i pick the name, however, as deconv is the most common name especially for beginner, i decide to use this name.
