### ISSUE TITLE
Recall the model script, it shows error

### ISSUE THREAD

**Issue by ruanxt** [zsdonghao/tensorlayer#139]
I write my training script as a function, and after running the training, then I recall it, it shows error:

```
    \nHint : Use different name for different 'Layer' (The name is used to control parameter sharing)" % name)
Exception: Layer 'input_layer' already exists, please choice other 'name' or reuse this layer            
Hint : Use different name for different 'Layer' (The name is used to control parameter sharing)
```

It seems the data info in the old call is still there, why the data from different calls of the same script not independent of each other?

**Comment by zsdonghao** [comment]
if you want to reuse your model, see section 3 in this repo: https://github.com/wagamamaz/tensorlayer-tricks

**Comment by ruanxt** [comment]
Thanks! This doesn't work very well for me, because I set up multiple independent running separately, the scripts don't whether the model is available or not. Anyway, at last I figured out the solution, that is, just reset the default graph using:
```
tf.reset_default_graph()
```

**Comment by zsdonghao** [comment]
cool it is solved, you are welcome.
