### ISSUE TITLE
A transfer learning example to load pre-trained weights of keras or slim? 

### ISSUE THREAD

**Issue by wangg12** [zsdonghao/tensorlayer#140]
The doc just tells how to connect keras or slim layers, but how to load their pre-trained weights, and do further finetuning?

**Comment by zsdonghao** [comment]
if you get a variables list in order, you can use `tl.files.assign`;  if you get a ckpt, you can use tensorflow 's method.

**Comment by zsdonghao** [comment]
oh, i forgot to send you this link : https://github.com/zsdonghao/tensorlayer/blob/master/example/tutorial_inceptionV3_tfslim.py

**Comment by wangg12** [comment]
Thanks.
