### ISSUE TITLE
Some unexpected problems

### ISSUE THREAD

**Issue by imhuay** [zsdonghao/tensorlayer#142]
When I run the tutorial_mnist.py on Windows10, it didn't success at first
```Traceback (most recent call last):
  File "tutorial_mnist.py", line 582, in <module>
    sess = tf.InteractiveSession()
  File "tutorial_mnist.py", line 34, in main_test_layers
    tl.files.load_mnist_dataset(shape=(-1,784))
  NameError: name 'np' is not defined
```
Then I run the tutorial_mnist_simple.py, another problem:
```SyntaxError: encoding problem: utf8```

So I change to utf-8. 
Then the two examples all run successfully

**Comment by zsdonghao** [comment]
thank you for reporting that.
