### ISSUE TITLE
Attempt to reuse RNNCell with a different variable scope than its first use

### ISSUE THREAD

**Issue by CTTC** [zsdonghao/tensorlayer#144]
It seems that TensorFlow 1.1 has made some changes to how to use the `tf.contrib.rnn.MultiRNNCell`, please check [here](https://github.com/tensorflow/tensorflow/commit/e8482ab23bd0fce5c2941f6a190158bca2610a35) and (https://github.com/tensorflow/tensorflow/issues/8191)

For example,the current code inside `tl.layers.DynamicRNNLayer` only works in TensorFlow 1.0, not in TensorFlow 1.1. It will raise error shown in the title if TensorFlow 1.1 is used.

I changed the source code in `tl.layers.DynamicRNNLayer` to this, and it works again.
```python
self.cell = MultiRNNCell_fn([self.cell] * n_layer, state_is_tuple=True)
```
changed to:
```python
self.cell = MultiRNNCell_fn([tf.contrib.rnn.DropoutWrapper(cell_fn(num_units=n_hidden, **cell_init_args), input_keep_prob=in_keep_prob, output_keep_prob=1.0) for _ in range(n_layer)], state_is_tuple=True)
```
Can you update the RNN code for the latest TensorFlow? @zsdonghao  Thanks.

**Comment by zsdonghao** [comment]
@CTTC Many thanks for your report.

Could you make a push request, because this is your contribution.

To make it works for all version, you may like to change as follow.
```python
try: # TF1.1
     xxx
except:  # TF1.0
     xxx
```

Thanks in advance.

**Comment by CTTC** [comment]
@zsdonghao  Sorry for the late reply. I'm happy to make a pull request. I will submit it ASAP.

**Comment by zsdonghao** [comment]
@CTTC thank you very much indeed.
