### ISSUE TITLE
Encounter a problem when pre-training embedding matrix

### ISSUE THREAD

**Issue by Lieutenant-Tom** [zsdonghao/tensorlayer#156]
when I use tutorial_word2vec_basic.py to train an embedding matrix, I got a mistake:
`could not broadcast input array from shape (50000,128) into shape (50000)`, and I found that the function tl.files.save_npz didn't work. I tried to change the source code`np.savez(name, params=save_list_var)` to `np.savez(name, params=save_list_var[0])`, and it worked. But I have no idea why the original code didn't work well.

**Comment by zsdonghao** [comment]
thank you for your report ~
could you tell me your operation system, python version, tensorflow and tensorlayer version? 
then i can have a check.
many thanks

**Comment by zsdonghao** [comment]
please reopen if there is a bug in TL.
