### ISSUE TITLE
Dropout settings in DynamicRNNLayer

### ISSUE THREAD

**Issue by craigleehi** [zsdonghao/tensorlayer#158]
Hi,

First of all, thanks for this great library!

I was wondering why the `output_keep_prob` in the implementation of [DynamicRNNLayer](https://github.com/zsdonghao/tensorlayer/blob/master/tensorlayer/layers.py#L3964) is always `1.0`. It contradicts the documentation of the parameter `dropout `. The same story for [BiDynamicRNNLayer](https://github.com/zsdonghao/tensorlayer/blob/master/tensorlayer/layers.py#L4208).

**Comment by zsdonghao** [comment]
With multiple RNN layer, we only need to add `input_keep_prob ` to the hidden outputs between different RNN layers. In the last RNN layer, we can see we add `output_keep_prob` as below:

```python
        if dropout:
            self.cell = DropoutWrapper_fn(self.cell,
                      input_keep_prob=1.0, output_keep_prob=out_keep_prob)
```

**Comment by craigleehi** [comment]
@zsdonghao Thanks for the reply.

**Comment by craigleehi** [comment]
@zsdonghao But the above code is not included in the BiDynamicRNNLayer.
