### ISSUE TITLE
save_npz sometimes fails

### ISSUE THREAD

**Issue by craigleehi** [zsdonghao/tensorlayer#160]
Hi,

`save_npz` sometimes fails because of [this line of code](https://github.com/zsdonghao/tensorlayer/blob/master/tensorlayer/files.py#L552), where `params` is a `list` of numpy arrays. When the first dimension of arrays in `params` is the same but other dimensions may be not, numpy would raise a broadcast error.

Here is a piece of code for reproducing the numpy error.

> import numpy as np
> t1 = np.arange(8).reshape((2, 2, 2))
> t2 = np.arange(12).reshape((2, 2, 3))
> t3 = np.arange(16).reshape((2, 2, 4))
> np.savez('test.npz', params=[t1, t2, t3])

I use python 3.5 and numpy 1.12. I googled around and it seems to be an implementation problem in numpy, as suggested by [this](https://stackoverflow.com/questions/25552741/python-numpy-not-saving-array). A possible solution is not to use a list of numpy arrays for the `params`.

**Comment by zsdonghao** [comment]
thank you for reporting this.

Could we set all params to list before saving them?

`np.savez('test.npz', [list(t1),list(t2),list(t3)])`

**Comment by craigleehi** [comment]
@zsdonghao the error would still be raised.
