### ISSUE TITLE
problem when using DynamicRNNLayer 

### ISSUE THREAD

**Issue by liu11liu11** [zsdonghao/tensorlayer#170]
i think we should define cell_fn in the way of reuse in DynamicRNNLayer.
ValueError: Attempt to have a second RNNCell use the weights of a variable scope that already has weights: 'model/dynamic_rnn/rnn/basic_lstm_cell'; and the cell was not constructed as BasicLSTMCell(..., reuse=True).  To share the weights of an RNNCell, simply reuse it in your second calculation, or create a new one with the argument reuse=True.
。
 codes like the follow:

 input_data = tf.placeholder(tf.float32, [batch_size, None,2])
    targets = tf.placeholder(tf.float32, [batch_size, None])
    # Testing (Evaluation)
    input_data_test = tf.placeholder(tf.int32, [1, 1])
    targets_test = tf.placeholder(tf.int32, [1, 1])

    def inference(x, is_training, num_steps, reuse=None):
        """If reuse is True, the inferences use the existing parameters,
        then different inferences share the same parameters.
        Note :
        - For DynamicRNNLayer, you can set dropout and the number of RNN layer internally.
        """
        print("\nnum_steps : %d, is_training : %s, reuse : %s" %
                                                (num_steps, is_training, reuse))
        initializer = tf.random_uniform_initializer(init_scale, init_scale)
        with tf.variable_scope("model", reuse=reuse):
            tl.layers.set_name_reuse(reuse)
            network = tl.layers.InputLayer(
                        inputs = x,
                        name ='layer')
            network = tl.layers.DynamicRNNLayer(network,
                                      cell_fn = tf.contrib.rnn.BasicLSTMCell,
                                      n_hidden = 2,
                                      dropout = 0.7 if is_train else None,
                                      sequence_length = None,
                                      #sequence_length = DynamicRNNLayer.retrieve_seq_length_op2(a),
                                      return_seq_2d = False,     # stack denselayer or compute cost after it
                                      name = 'dynamic_rnn')
            network = tl.layers.DropoutLayer(network, keep=keep_prob, is_fix=True, is_train=is_training, name='drop1')
          # Alternatively, if return_seq_2d=False, in the above RNN layer,
            # you can reshape the outputs as follow:
            network = tl.layers.ReshapeLayer(network,
                  shape=[-1, int(network.outputs._shape[-1])], name='reshape')
            network = tl.layers.DenseLayer(network,
                        n_units=1,
                        W_init=tf.random_uniform_initializer(-init_scale, init_scale),
                        b_init=tf.random_uniform_initializer(-init_scale, init_scale),
                        act = tf.identity, name='output_layer')
        return network, lstm1

    # Inference for Training
    network, lstm1 = inference(input_data,
                            is_training=True, num_steps=num_steps, reuse=None)
    # Inference for Validating
    network_val, lstm1_val = inference(input_data,
                            is_training=False, num_steps=num_steps, reuse=True)
    # Inference for Testing (Evaluation)
    network_test, lstm1_test = inference(input_data_test,
                            is_training=False, num_steps=1, reuse=True)

**Comment by zsdonghao** [comment]
this problem is the same as this one :  https://github.com/zsdonghao/text-to-image/issues/2

please have a look.

actually if you use TF1.2 , it will automatically reuse the RNN cell.~

**Comment by liu11liu11** [comment]
thanks!
