### ISSUE TITLE
Please give a unique name to tl.cost.cross_entropy for TF1.0+

### ISSUE THREAD

**Issue by HudsonHuang** [zsdonghao/tensorlayer#171]
Running minist example with Tensorflow 1.2 in [documents](http://tensorlayercn.readthedocs.io/zh/latest/user/tutorial.html)
shows error of :
`"Please give a unique name to tl.cost.cross_entropy for TF1.0+"`

in line 36 of the example code:
`cost = tl.cost.cross_entropy(y, y_)`
should be change to:
`cost = tl.cost.cross_entropy(y, y_,name='cost')`
and it works.

运行官方[MNIST例子](http://tensorlayercn.readthedocs.io/zh/latest/user/tutorial.html)
报错：
`"Please give a unique name to tl.cost.cross_entropy for TF1.0+"`

在例子代码的第 36 行:
`cost = tl.cost.cross_entropy(y, y_)`
应该被改为:
`cost = tl.cost.cross_entropy(y, y_,name='cost')`
便可正常工作

**Comment by zsdonghao** [comment]
谢谢您，这个细节是您发现的，请问能否在 https://github.com/shorxp/tensorlayer-chinese/blob/master/docs/user/tutorial.rst 弄个push request，我可以merge一下。
