### ISSUE TITLE
How do I format a dataset for training in Python?

### ISSUE THREAD

**Issue by alialani12** [zsdonghao/tensorlayer#173]
I have 3000 grayscale BMP images of some handwritten digits (just like MNIST). Now I want to train my model with this dataset (I am using the Keras library) and I am using a convolution neural network for training.

I am using this code to convert one of the images into array

    `import numpy
    from PIL import Image
    import matplotlib.pyplot as plt
    import matplotlib.image as mpimg
    import numpy as np
    img = Image.open(open('CMATERdb 3.3.1\Ad02599.bmp')).convert("L")
    print(img.format, img.size, img.mode)
    img = numpy.asarray(img) / 255.
    imgplot = plt.imshow(img)`

**and the result from the code was** 

None (32, 32) L

![image](https://user-images.githubusercontent.com/25184963/27939956-8758b288-62d0-11e7-90df-62ccfaf09df6.png)

Any help how I can convert all images and put them in the same MNIST datast format that will be highly appreciated.

**Comment by zsdonghao** [comment]
make the image shape to be 3 D
img = np.asarray(img)
img.shape = 32, 32, 1

and make the dataset to be 4 D:  [n_examples, 32, 32, 1]

**Comment by alialani12** [comment]
Thanks for reply, please can you give more details because I am new in this environment.

**Comment by zsdonghao** [comment]
Hi, if you use CNN just simply follow the CNN example in `tutorial_mnist.py`, make your shape to [3000, 32, 32, 1].

If you use MLP, flatten your data into [3000, 32x32].
