### ISSUE TITLE
DownSampling2dLayer's size parameter as scale makes error

### ISSUE THREAD

**Issue by ShieLian** [zsdonghao/tensorlayer#174]
layers.py#L1605
layers.py#L1606
layers.py#L1610
layers.py#L1611
When pass size=0.25, is_scale=True, the size produced in these line will be 1D float32 tensor, which makes tensorflow raise an error.
The size calculated should be cast to int.

**Comment by zsdonghao** [comment]
thank you for reporting this, i make a new commit to fix this problem, please check [this](https://github.com/zsdonghao/tensorlayer/commit/2a2422934b33ec189453cbc54e442b910c3cc2f1) if you like.
