### ISSUE TITLE
SubpixelConv2d is too slow when construct a graph

### ISSUE THREAD

**Issue by ShieLian** [zsdonghao/tensorlayer#175]
The reason may be in layers.py#L2191, the loop adds too many ops.
An alternative way is as follow:
Assume input feature maps X is b\*h\*w\*(r^2\*c) tensor,
`Xs=tf.split(X,r,3) #b*h*w*r*r`
`Xr=tf.concat(Xs,2) #b*h*(r*w)*r`
`X=tf.reshape(Xr,(b,r*h,r*w,c)) # b*(r*h)*(r*w)*c`
Then X is the return value in L2197

This way only add three ops in the graph, and for an feature map 24*24*64, the time constructing the graph is much more short.
Also, time for constructing train-ops is shorten.

layers.py#L2188 to L2196 need to change, and L2170 to L2186 can be removed.

**Comment by zsdonghao** [comment]
Thank you for your advice. As it should be your credit, It is possible that you can contribute your code via push request?
Many thanks.

**Comment by ShieLian** [comment]
Create PR #176
