### ISSUE TITLE
Can you provide SubpixelConv1d function?

### ISSUE THREAD

**Issue by 42binwang** [zsdonghao/tensorlayer#177]

**Comment by zsdonghao** [comment]
Do you have any paper that relate to subpixel convolution on 1D data?

**Comment by 42binwang** [comment]
Yes, Please refer to this one **AUDIO SUPER-RESOLUTION USING NEURAL NETS**. And, here is their implementation of 1d subpixel, https://github.com/kuleshov/audio-super-res/blob/master/src/models/layers/subpixel.py

**Comment by zsdonghao** [comment]
thanks for your link, i already merge this function into `SubpixelConv1d`, please have a try.

**Comment by 42binwang** [comment]
Thank you.
