### ISSUE TITLE
Redundand sess=Session() and missing sess.close() in example tutorial_mnist.py

### ISSUE THREAD

**Issue by LiekkasWhy** [zsdonghao/tensorlayer#178]
In file tensorlayer/example/tutorial_mnist.py.

In each function in this file, the variable sess is initialized separately. However, in line 582, there is a redundant assignment to the global variable sess,  which is actually useless.

In function main_test_cnn_layer(), no sess.close() is invoked.

**Comment by zsdonghao** [comment]
you can make a push request for this
