### ISSUE TITLE
tl.prepro.threading_data gave no performance gain for lots of small images

### ISSUE THREAD

**Issue by geometrikal** [zsdonghao/tensorlayer#179]
Using `tl.prepro.threading_data` did not give me a significant improvement for batches of 200 x 64 x 64 x 1 with rotate, zoom and shift.

It looks like the function creates one thread for every image. Changing the function to create a thread for a subset of the images, and then using the `_multi` versions of the preprocessing functions speed things up 3x (for a thread count of 8).

Code is below:

    def threading_data(self, data=None, thread_count=8, fn=None, **kwargs):
        def apply_fn(results, i, data, kwargs):
            results[i] = fn(data, **kwargs)
        split = int(math.ceil(len(data) / thread_count))
        thread_count = int(math.ceil(len(data) / split))
        results = [None] * thread_count
        threads = []
        for i in range(thread_count):
            t = threading.Thread(
                name='threading_and_return',
                target=apply_fn,
                args=(results, i, data[i*split:(i+1)*split,:,:,:], kwargs)
            )
            threads.append(t)
        for t in threads:
            t.start()
        for t in threads:
            t.join()
        return np.concatenate(results)

**Comment by luomai** [comment]
This is an expected behaviors of threading_data as it is not created for applying functions onto massive objects. What is the length of data in your use case?

**Comment by zsdonghao** [comment]
Hi, do you mean if the batch size is big, your implementation is better than the existing one?

If yes, could you make a PR to merge your implementation with the existing one? 

```python
def threading_data(self, data=None, thread_count=None, fn=None, **kwargs):
    if thread_count is None:
        use existing one.
   else:
        use your one.
```

Many thanks.

**Comment by geometrikal** [comment]
@luomai batch size of 200 images with size 64 x 64 x 1. I followed the training part of the code from `tutorial_cifar10.py'

 @zsdonghao Yes, batch size of 200, but not that different to batch size of 128 used in `tutorial_cifar10.py'. I will try to make a PR.

**Comment by geometrikal** [comment]
I can get even more performance gain using multiprocessing.Pool, will try to add another function

**Comment by zsdonghao** [comment]
@geometrikal Cool, that is great~

Please make sure your new function can compatible with old code, otherwise, other user will need to change their codes.

Many thanks.

**Comment by geometrikal** [comment]
@zsdonghao 

Is it possible to go from
    threading_data(self, data=None, fn=None, **kwargs):
to:
    threading_data(self, data=None, thread_count=8, fn=None, **kwargs):

If the user was not using named arguments?

e.g. in the examples you have `threading_data(X, zoom_multi, zoom_range=[0.5, 1], is_random=True)` which I have changed to `threading_data(X, None, zoom_multi, zoom_range=[0.5, 1], is_random=True)`

Or better to have a new function entirely?

**Comment by geometrikal** [comment]
Pull request #180 added

**Comment by zsdonghao** [comment]
I think `threading_data(self, data=None, fn=None, thread_count=None, **kwargs):`  is better?

**Comment by geometrikal** [comment]
Updated

**Comment by geometrikal** [comment]
Pull request merged
