### ISSUE TITLE
prepro apply_transform interpolation uses order=0 (nearest neighbour) resulting in images with artifacts

### ISSUE THREAD

**Issue by geometrikal** [zsdonghao/tensorlayer#181]
Default for `scipy.ndimage.interpolation` is `order=3` which results in smooth images. Using `order=0` in tensorlayer `apply_transform` function results in images with artefacts.

Suggest to change to `order=3`

Order = 0

![order0](https://user-images.githubusercontent.com/1187528/28710383-fde7cea2-7383-11e7-853a-157b3e16edc7.png)

Order = 3

![order3](https://user-images.githubusercontent.com/1187528/28710388-04331fb4-7384-11e7-8b2a-eaf7b4149967.png)

**Comment by zsdonghao** [comment]
great, please make another PR~
