### ISSUE TITLE
Maybe an introduction mistake in layers.py

### ISSUE THREAD

**Issue by lishiyuwhu** [zsdonghao/tensorlayer#184]
in 1222 line, `    use_cudnn_on_gpu : an optional string from: "NHWC", "NCHW". Defaults to "NHWC".
    data_format : an optional bool. Defaults to True.`

should be:
use_cudnn_on_gpu: An optional bool. Defaults to True.
data_format: An optional string from: "NHWC", "NCHW"， 默认为"NHWC"

**Comment by zsdonghao** [comment]
thanks, i fix it now~
