### ISSUE TITLE
Add new backend other than TensorFlow

### ISSUE THREAD

**Issue by arita37** [zsdonghao/tensorlayer#185]
Hello,

Am working on a project using more Chainer (and potentially PyTorch) as computationnal backend.
https://chainer.org/

How can we plug-in to TensorLayer ?
Especially, do you have a doc to develope the connector for TensorLayer ?

It would be very useful to have generic connector API to connect other computationnal backend.

**Comment by zsdonghao** [comment]
Hi @arita37 ,  TensorLayer is a fully transparent library for TensorFlow only, so I think it may very difficult to have other backend~

**Comment by arita37** [comment]
Hello,

That a bit the opposite of tensorlayer purpose....., having flexible framework for deep learning process...

This is not very flexible.....

Can you create layer to add other backend ? (Like PyTorch, Chainer,...)








On 3 Aug 2017, at 19:57, Hao <notifications@github.com> wrote:

Hi @arita37 , TensorLayer is a fully transparent library for TensorFlow only, so I think it may very difficult to have other backend~

―

**Comment by parisburn** [comment]
@arita37 This is not the purpose of TensorLayer to provide support for different backend. If you do serious deep learning, there is no matter of using which backend. Developers for TensorLayer are aiming at include as many opensource codes as possible to cover different models. If you are interested in particular function in PyTorch, why not contribute for TensorLayer? When TensorLayer mentioned flexible, it means it can build a network architecture easily definitely not support everything.

**Comment by arita37** [comment]
Hello,

You should precise the meaning of "flexible" because it says it aims at different backend for DB...


The question why people develop different Deep Learning framework:
Torch, Theano, Neon, Nabble, Tensorflow, Chainer, Caffe, ....
since a CNN / RNN have same equations and  definitions in all of them....????

Reason:
   Computation strategy are different.
   There are benefits from different computation strategy even for same NN.

  Which the same for Database.
  That's why, SQLachemy exists and SQL request exist : to unify data request whatever database software you have behind.


At the definition level (layer), ex: CNN,
from mathematical/formalism, this is same. This is the most important point.


Why not extend TensorLayer as network generator which make it a very versatile framework, even for future not yet released backend ?



















On 3 Aug 2017, at 20:18, Aaron <notifications@github.com> wrote:

@arita37 This is not the purpose of TensorLayer to provide support for different backend. If you do serious deep learning, there is no matter of using which backend. Developers for TensorLayer are aiming at include as many opensource codes as possible to cover different models. If you are interested in particular function in PyTorch, why not contribute for TensorLayer? When TensorLayer mentioned flexible, it means it can build a network architecture easily definitely not support everything.

―

**Comment by zsdonghao** [comment]
@arita37 hi, if you read TL's code you will find the "flexibility" of layer is for TF only at the moment.

### WHY

A small example as follow, you can pass the activation function into a layer like that, so when you have a customized activation function, you can also pass it to the layer.

```python
n = InputLayer(x, name='in')
n = DenseLayer(n, 100, tf.nn.relu, name='d1')
```
But if you want this layer to support other backend like Chainer, you can't pass TF's activation function. So if the layer supports both Chainer and TF, the code to build a layer would become `DenseLayer(n, 100, "relu", name='d1')`, and it is not "transparent" to TF any more. (to support both TF and Theao, which is similar to the Keras design).

The design philosophy of TL as follow, the goal of our flexibility is for TF only.

- Simplicity : TensorLayer lifts the low-level dataflow interface of TensorFlow to high-level deep learning modules. These modules come with detailed examples that can be deployed in minutes. A user may find it easy to bootstrap with TensorLayer, and then dive into module implementation if need.
- Composability : If possible, deep learning modules should be composed, not built. By offering connectors to TF-Slim and Keras, TensorLayer can be used to glue existing pieces together. This yields a much better time to develop ideas and allows easy module plug-in.
- Flexibility : A deep learning workflow can require many careful tunings. TensorLayer provides the access to the native APIs of TensorFlow and therefore help users to achieve a flexible control within the engine.
- Performance : TensorLayer provides zero-cost compatibility for TensorFlow. It can easily run on heterogeneous platforms or multiple servers while offering native TensorFlow performance.


### SOLUTION

I think the better way to support other backends is to build other sets of layer:

`tl.layers` for TF
`tl.layers_xx` for others

so users can still able to use other toolboxs like `tl.prepro` etc.

**Comment by zsdonghao** [comment]
feel free to reopen the discussion
