### ISSUE TITLE
Issues with ops.exit_tf function

### ISSUE THREAD

**Issue by Ericvulpi** [zsdonghao/tensorlayer#188]
So far I've 2 issues with this function :
- ops.exit_tf() returns an error because a session is expected as argument.
- ops.exit_tf(sess) returns "NameError: name 'exit' is not defined" when launched from an IPython console - in my case it's Spyder's internal IPython console (tested both on Mac and Windows)

Both issue are easy to solve :
- add `if sess != None:` before `sess.close()`
- use `from sys import exit as _exit` to avoid whatever is the interference that's throwing the error

Before I propose a pull request, I just wanted to check that I'm not misusing the function : I tried to use the function without an argument to easly exit tensorboard (which is a nice feature) and I'm launching it from IPyton instead of the terminal because it's seems like a usefull function to be able to include in a script (and i run my scripts from Spyder)

**Comment by zsdonghao** [comment]
Hi, in my view the changes are all correct, thank you.

**Comment by Ericvulpi** [comment]
OK, will do a PR tomorrow.

Side note : I went quickly through your docs and you mention in the Testing section of Development that you want a test case for each bug fix. I'm guessing this is no longer required (since i can't find any test in the code)

**Comment by zsdonghao** [comment]
yes, it doesn't require.
