### ISSUE TITLE
out_keep_prob is not used in BiDynamicRNNLayer

### ISSUE THREAD

**Issue by lei-li** [zsdonghao/tensorlayer#190]
`out_keep_prob` defined in [BiDynamicRNNLayer](https://github.com/zsdonghao/tensorlayer/blob/b87f30ac49747c97fef73fb44aaed87248aebebf/tensorlayer/layers.py#L4708) is not used in the followed code sections, unlike the one in [DynamicRNNLayer](https://github.com/zsdonghao/tensorlayer/blob/b87f30ac49747c97fef73fb44aaed87248aebebf/tensorlayer/layers.py#L4501). The following code may be missing in the `BiDynamicRNNLayer`

```
        if dropout:
            self.fw_cell = DropoutWrapper_fn(self.fw_cell,
                      input_keep_prob=1.0, output_keep_prob=out_keep_prob)
            self.bw_cell = ...
```

**Comment by zsdonghao** [comment]
@lei-li i make a new commit, https://github.com/zsdonghao/tensorlayer/commit/8b2eaa41215fe6e682d8c69e1a6ce75e4b289ba5

please have a try.

**Comment by craigleehi** [comment]
@zsdonghao thanks for the quick move!

**Comment by lei-li** [comment]
@zsdonghao thanks for the quick move.
