### ISSUE TITLE
Request: Ability to use decoder previous output as decoder input in seq2seq model.

### ISSUE THREAD

**Issue by dbusbridge** [zsdonghao/tensorlayer#205]
At run time, I would like to be able to run my seq2seq model without advanced knowledge of what the model is aiming for (e.g. translating an out-of-corpus english sentence into french). To do this, I cannot have a set of decoder inputs pre-prepared, and need to rely on the output of the decoder itself.

Is there an easy way to do this with the current Seq2Seq layer, or is it quite a serious modification?

Cheers, Dan

**Comment by zsdonghao** [comment]
Hi, you can use the standard Seq2seq to do this http://tensorlayer.readthedocs.io/en/latest/modules/layers.html#simple-seq2seq
there is a example in the docs.

However, you still need to tokenize your sentence and feed the data during training by following this link https://arxiv.org/pdf/1409.3215v3.pdf

Hope it helps

**Comment by dbusbridge** [comment]
Hi - thanks for the response!

I'm really sorry, I feel like I'm missing something. In the docs, the main example given
```
>>>     net = Seq2Seq(net_encode, net_decode,
...             cell_fn = tf.contrib.rnn.BasicLSTMCell,
...             n_hidden = 200,
...             initializer = tf.random_uniform_initializer(-0.1, 0.1),
...             encode_sequence_length = retrieve_seq_length_op2(encode_seqs),
...             decode_sequence_length = retrieve_seq_length_op2(decode_seqs),
...             initial_state = None,
...             dropout = None,
...             n_layer = 1,
...             return_seq_2d = True,
...             name = 'seq2seq')
```
sets up a dependency of `net.outputs` upon both `net_encode` and `net_decode`. In that case, it is not possible for the graph to give me a value for `net.outputs` unless `net_encode.outputs` and `net_decode.outputs` both have values.

I would like the `DynamicRNNLayer` acting on `net_encode`, using the inputs to `net_encode` to give a final hidden state. Using this final hidden state, I would like the decoder `DynamicRNNLayer` to give me what it thinks should be the `target_sequence`, without being explicitly fed a target sequence. Absolutely, during training I will feed it the encode, decode and target sequences as appropriate (I have no masks as all of my sequences are the same length), but at inference time, I only want to feed it the encoder sequence, and it's not clear to me how to resolve this. I see that the `tutorial_translate` example can achieve this behaviour, but unfortunately it depends on functionality deprecated since TF 0.12.

Any help you can offer would be greatly appreciated, thanks again!

Dan

**Comment by zsdonghao** [comment]
Hi, i have had a script for this, but can't find it, and I just have a new commit for Seq2Seq.

For inferencing, you will need to reuse the model parameters and set the `decode_sequence_length` to 1 (just like the text generation example). Then after you get the `final_state_encode` of RNN encoder by feeding the encoding text, you feed the `final_state_encode` to Seq2Seq as the `initial_state_decode` of the RNN decoder, by doing this, you can get a new output and a new `final_state_decode`, so you can continuous to feed the `final_state_decode` as `initial_state_decode` and new output as `decode_seqs` to get the next output and `final_state_decode`.

Let me know if you still have problem.

**Comment by zsdonghao** [comment]
@dbusbridge I am reimplementing my previous Twitter Chatbot, will send the link to you later.

**Comment by dbusbridge** [comment]
Cool thanks! 

Your explanation of using single sequence lengths iteratively to construct the output sequence also made sense. I have something rough working but I'm still tidying it up.

**Comment by zsdonghao** [comment]
Hi, here is a simple Seq2Seq chatbot example without using `tf.contrib.seq2seq` and attention.
You can clearly see how to iterate the data during training and inferencing.

https://github.com/zsdonghao/seq2seq-chatbot

**Comment by dbusbridge** [comment]
Hey - that works great, thank you!
