### ISSUE TITLE
Missing variables in LayerNormLayer

### ISSUE THREAD

**Issue by craigleehi** [zsdonghao/tensorlayer#210]
Hi,

LayerNormLayer doesn't collect the variables in tf.contrib.layers.layer_norm.

https://github.com/zsdonghao/tensorlayer/blob/0ede6653e4c3f5504d285ba929d8d885e1967285/tensorlayer/layers.py#L3587

**Comment by zsdonghao** [comment]
Thanks, just fix it in master version

**Comment by craigleehi** [comment]
@zsdonghao I think the previous implementation that doesn't use tf.variable_scope is more reasonable. 

Current fix would produce `layernorm/LayerNorm/beta` and `layernorm/LayerNorm/gamma` variable names if the `name='layernorm'`

**Comment by zsdonghao** [comment]
Hi, use `tf.variable_scope` can help us get the variables using `variables = tf.get_collection(TF_GRAPHKEYS_VARIABLES, scope=vs.name)`, I now change the `scope=None` to `scope='var'`, it looks better

**Comment by craigleehi** [comment]
@zsdonghao Thanks for the reply! Sorry that I didn't make it clear. What I meant is 

```
        self.outputs = tf.contrib.layers.layer_norm(self.inputs,
                center=center,
                scale=scale,
                activation_fn=act,
                reuse=reuse,
                variables_collections=variables_collections,
                outputs_collections=outputs_collections,
                trainable=trainable,
                begin_norm_axis=begin_norm_axis,
                begin_params_axis=begin_params_axis,
                scope=name,
                )
        with tf.variable_scope(name) as vs:
            variables = tf.get_collection(TF_GRAPHKEYS_VARIABLES, scope=vs.name)
```
