### ISSUE TITLE
Couldn't use GPU to compute even I set tf.device('/gpu:0')

### ISSUE THREAD

**Issue by VisanXJ** [zsdonghao/tensorlayer#216]
![image](https://user-images.githubusercontent.com/26617552/31018091-692cb9a6-a55d-11e7-8159-a5fd99e625ac.png)

Code like above;
There is a strange things that  the GPU is selected to compute(the GPU occupancy is up to 80%) at begnning, but soon enough the GPU occupancy slow down to 1~2% until the epoch is done. Again, at the begging of second epoch computing, the GPU occupancy is up to 80%, like first epcoh ,the GPU occupancy  slow down quickly. Could you help me please

**Comment by zsdonghao** [comment]
First, make sure you can run TensorFlow in GPU mode.
Then, remove `tf.device` to see whether it run with GPU or not.
