### ISSUE TITLE
reverse the word embedding

### ISSUE THREAD

**Issue by SunnerLi** [zsdonghao/tensorlayer#226]
In general cases, 
the seq2seq model will be used to generate the corresponding output.
In my implementation, 
I want to use usual RNN to generate the sequence output.
However, 
I didn't find any method to transfer the output vectors to the index form.
As the result, I do it by myself [here](https://github.com/SunnerLi/Embedding-lookdown).

I just want to ask:
Is there any method to reverse the word embedding with the current tensorlayer API?
Since I didn't find, I code it by scratch in my program.

**Comment by zsdonghao** [comment]
hi, TL doesn't have a layer to transfer the output vectors to the index form.
For me, I usually get the index from a vector by `tl.nlp.sample` or `tl.nlp.sample_top`.

**Comment by SunnerLi** [comment]
Thanks for your recommendation! 
Before you suggest, I regard that tensorlayer just have `tl.layers` API...
Very appreciate!!!
