### ISSUE TITLE
Wrapper Function Tensorflow Error Handling 

### ISSUE THREAD

**Issue by chaos5958** [zsdonghao/tensorlayer#248]
I want to quit a program when it fails to upload checkpoint file. 
However, Tensolayer catches an exception (e.g. tf.errors.NotFoundErrors) inside a function and it only prints an error message.

How could I directly handle an error from tensorflow if a wrapper function already catches it?
If this problem is just easily handled by python programming, I'll close this issue. 

Besides, thank you a lot for awesome tensorflow library, I really enjoy it!

    def load_ckpt(sess=None, mode_name='model.ckpt', save_dir='checkpoint', var_list=[], is_latest=True, 
    printable=False):

    try:
        saver = tf.train.Saver(var_list)
        saver.restore(sess, ckpt_file)
    except Exception as e:
        print(e)
        print("[*] load ckpt fail ...")

**Comment by zsdonghao** [comment]
@chaos5958 , to make it easy, I suggest you to copy the code inside this API. Could I know what is the error about?

**Comment by chaos5958** [comment]
@zsdonghao, Actually, this is not error, but suggestion for improving Tensorlayer.
I found Tensorlayer is extremely useful for people who want to use parts of tensorflow semantics and control tensorflow semantics in detail.
However, above example might be limitation of Tensorlayer, since we can't control errors occurred from Tensorflow if we don't modify APIs itself as you suggested. 

Then, let's close this issue and, I'll send a pull request if I can design better code.

Thank you for answering me,
Hyunho
