### ISSUE TITLE
How can I use summaries with tensorlayer

### ISSUE THREAD

**Issue by nina124** [zsdonghao/tensorlayer#29]
Tensorboard is really powerful in tracking the training process. Currently, does tensorlayer support summaries?
E.g. with the netwrok stacked by several tensorlayers , I want to use  _histogram_summary_ to view the last layer's activation  and use _scalar_summary_ to record the sparsity rate of  last layer's activation by _tf.nn.zero_fraction_.
I tried the following code in a wish to achieve the above purpose, but failed.

`
tf.histogram_summary(tensor_name + '_activations', network.output)
tf.scalar_summary(tensor_name + '_sparsity', tf.nn.zero_fraction(network.output))
`

If there is any way to track the summaries with tensorlayer, please notify me. And if there is none, could you add this support in tensorlayer?

**Comment by zsdonghao** [comment]
check this [PR](https://github.com/zsdonghao/tensorlayer/pull/78) by @JoelKronander
