### ISSUE TITLE
Error：Use different name for different 'Layer'

### ISSUE THREAD

**Issue by jindongwang** [zsdonghao/tensorlayer#32]
Hi, I am using TensorLayer with Tensorflow to accomplish some classification task.
Basically I use cross validation technique to gain some trustworthy results. The outline of my code is: first get different training and testing sets, then feed them into the model.
A very interesting question is that in TensorLayer, every layer requires a name, which is necessary or it will be an error. For me, I compacted the model thing into a whole function called model_training(), which takes inputs from every training/test sets.
Here comes the erros: in the function, I basically give every layer a name, say, "input_layer". For a single round of model training, this works fine. But for multiple rounds, it just says `Use different name for different 'Layer'`. It seems a little bizzar. I did initialized session every time. Here is the code:
![qq 20161205215050](https://cloud.githubusercontent.com/assets/6158206/20887291/f72cb242-bb34-11e6-941e-5ccccc01c0a7.png)
![qq 20161205215101](https://cloud.githubusercontent.com/assets/6158206/20887296/faff9628-bb34-11e6-962b-7ec2b9d208d0.png)

And I get the following error:
`Traceback (most recent call last):
  File "H:/projects/python/parkinson/main.py", line 115, in <module>
    train_model(x_train,x_test,y_train,y_test)
  File "H:/projects/python/parkinson/main.py", line 69, in train_model
    network = tl.layers.InputLayer(inputs=x,name='input_layer')
  File "C:\Users\jindongwang\Anaconda3\lib\site-packages\tensorlayer\layers.py", line 271, in __init__
    Layer.__init__(self, inputs=inputs, name=name)
  File "C:\Users\jindongwang\Anaconda3\lib\site-packages\tensorlayer\layers.py", line 201, in __init__
    \nHint : Use different name for different 'Layer' (The name is used to control parameter sharing)" % name)
Exception: Layer 'input_layer' already exists, please choice other 'name'.            
Hint : Use different name for different 'Layer' (The name is used to control parameter sharing)`

It seems after the first round of training, the errors occurs.
Is there any way to fix this?

**Comment by zsdonghao** [comment]
As you are doing cross validation, actually you have different models, you can use the following script to creates different inference for different fold.

```python
def inference(x, reuse=False, name='fold1'):
       with tf.variable_scope("model", reuse=reuse):
           tl.layers.set_name_reuse(reuse)
           network = tl.layers.InputLayer(inputs=x,name=name+'input_layer')
           network = tl.layers.DropoutLayer(network,keep=0.8,name=name+'drop1')
           network = tl.layers.DenseLayer(network,n_units=32,act=tf.nn.tanh,name=name+'relu1')
           ....
      return network
```
TensorLayer forces user to use different name for every layers so as to prevent bugs.

**Comment by jindongwang** [comment]
I see, thank you!
