### ISSUE TITLE
Apply activation function to RNN output

### ISSUE THREAD

**Issue by lucidfrontier45** [zsdonghao/tensorlayer#36]
Hi all.

I want to apply activation function to the output of RNNLayer.
However the `RNNLayer` has no `act` argument as `DenseLayer` or Convolution layers have.

```python
class tensorlayer.layers.RNNLayer(layer=None, cell_fn=<class 'tensorflow.python.ops.rnn_cell.BasicRNNCell'>, cell_init_args={}, n_hidden=100, initializer=<function _initializer>, n_steps=5, initial_state=None, return_last=False, return_seq_2d=False, name='rnn_layer')
```

I currently use the `LambdaLayer` to apply activation as follows. 

```python
net = tl.layers.RNNLayer(net, ...)
net = tl.layers.LambdaLayer(net, lambda x: act_fn(x))
```

where `act_fn` is a function such as `tf.nn.relu`.

Is it correct usage or is there any other way? 

Thank you.

**Comment by zsdonghao** [comment]
You can do in 2 ways.
1. `net = tl.layers.LambdaLayer(net, tf.nn.relu)`
2. `net.outputs = tf.nn.relu(net.outputs)`

**Comment by lucidfrontier45** [comment]
@zsdonghao 

Thank you. 

I think `act` should be included in `RNNLayer` so that the API is consistent to other Layers like Dense or Convolution.
 
Will `RNNLayer` be modified to have `act` in the future?

**Comment by zsdonghao** [comment]
we don't have plan to include `act` to `RNNLayer`, it is unusual to apply `act` just after RNNs.

**Comment by lucidfrontier45** [comment]
>it is unusual to apply act just after RNNs.

Its good to know that I am doing something wrong.

Thank you.
