### ISSUE TITLE
Installs into site-packages/data

### ISSUE THREAD

**Issue by geometrikal** [zsdonghao/tensorlayer#37]
On windows `pip install tensorflow` puts `imagenet_classes.py` into `site-packages/data`.

This seems like a pretty generic package name to write into... Was this intended?

**Comment by wagamamaz** [comment]
`data/imagenet_classes.py` contains imagenet label list which will be used in VGG, Inception examples.

**Comment by geometrikal** [comment]
Can you shift it to site-packages/tensorlayer/data instead of site-packages/data? At the moment if I try to import from my own data.py file the data package installed by tensorlayer is used instead.

**Comment by zsdonghao** [comment]
I moved data folder into example folder.
