### ISSUE TITLE
Why these errors?How to solve?

### ISSUE THREAD

**Issue by NeutronT** [zsdonghao/tensorlayer#38]
Code:

1. import tensorflow as tf
2. import tensorlayer as tl
3. import numpy as np
4. from PIL import Image
5. import os
6. 
7. 
8. def _int64_feature(value):
9.     return tf.train.Feature(int64_list=tf.train.Int64List(value=[value]))
10. 
11. 
12. def _bytes_feature(value):
13.     return tf.train.Feature(bytes_list=tf.train.BytesList(value=[value]))
14. 
15. 
16. path_save = r'W:/PlantClassification/'
17. path_train = r"W:/PlantClassification/train/"
18. classes = [str(i) for i in list(range(7))]
19. writer = tf.python_io.TFRecordWriter(path_save + 'train.tfrecords')
20. for index, name in enumerate(classes):
21.     class_path = path_train + name + '/'
22.     for img_name in os.listdir(class_path):
23.         img_path = class_path + img_name
24.         img = Image.open(img_path)
25.         img = img.resize((227, 227))
26.         img_raw = img.tobytes()
27.         example = tf.train.Example(features=tf.train.Features(feature={
28.             'label': _int64_feature(index),
29.             'img_raw': _bytes_feature(img_raw)}))
30.         writer.write(example.SerializeToString())
31. writer.close()
32. 
33. 
34. def read_and_decode(filename):
35.     filename_queue = tf.train.string_input_producer([filename])
36.     reader = tf.TFRecordReader()
37.     _, serialized_example = reader.read(filename_queue)
38.     features = tf.parse_single_example(serialized_example,
39.                                        features={
40.                                            'label': tf.FixedLenFeature([], tf.int64),
41.                                            'img_raw': tf.FixedLenFeature([], tf.string),
42.                                        })
43.     # You can do more image distortion here for training data
44.     img = tf.decode_raw(features['img_raw'], tf.float32)
45.     img = tf.reshape(img, [227, 227, 3])
46.     label = tf.cast(features['label'], tf.int32)
47.     return img, label
48. 
49. 
50. img, label = read_and_decode(r"W:\PlantClassification\train.tfrecords")
51. img_batch, label_batch = tf.train.shuffle_batch([img, label],
52.                                                 batch_size=4,
53.                                                 capacity=150000,
54.                                                 min_after_dequeue=2000,
55.                                                 num_threads=4)
56. 
57. 
58. init = tf.global_variables_initializer()
59. with tf.Session() as sess:
60.     sess.run(init)
61.     coord = tf.train.Coordinator()
62.     threads = tf.train.start_queue_runners(sess=sess, coord=coord)
63. 
64.     for i in range(3):
65.         print("Step %d" % i)
66.         val, l = sess.run([img_batch, label_batch])
67.         print(val.shape, l)
68.         tl.visualize.images2d(val, second=1, saveable=False, name='batch' + str(i), dtype=np.uint8, fig_idx=2020121)
69. 
70.     coord.request_stop()
71.     coord.join(threads)
72.     sess.close()
73. 

Error:
S:\Python35\python.exe W:/PlantClassification/visualize_data.py
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:128] successfully opened CUDA library cublas64_80.dll locally
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:128] successfully opened CUDA library cudnn64_5.dll locally
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:128] successfully opened CUDA library cufft64_80.dll locally
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:128] successfully opened CUDA library nvcuda.dll locally
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:128] successfully opened CUDA library curand64_80.dll locally
img_batch   : (4, 227, 227, 3)
label_batch : (4,)
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:885] Found device 0 with properties: 
name: GeForce GTX 960
major: 5 minor: 2 memoryClockRate (GHz) 1.1775
pciBusID 0000:01:00.0
Total memory: 2.00GiB
Free memory: 1.64GiB
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:906] DMA: 0 
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:916] 0:   Y 
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 960, pci bus id: 0000:01:00.0)
Step 0
W c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:975] Invalid argument: Input to DecodeRaw has length 154587 that is not a multiple of 4, the size of float
	 [[Node: DecodeRaw = DecodeRaw[little_endian=true, out_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](ParseSingleExample/Squeeze_img_raw)]]
W c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:975] Invalid argument: Input to DecodeRaw has length 154587 that is not a multiple of 4, the size of float
	 [[Node: DecodeRaw = DecodeRaw[little_endian=true, out_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](ParseSingleExample/Squeeze_img_raw)]]
W c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:975] Invalid argument: Input to DecodeRaw has length 154587 that is not a multiple of 4, the size of float
	 [[Node: DecodeRaw = DecodeRaw[little_endian=true, out_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](ParseSingleExample/Squeeze_img_raw)]]
W c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:975] Invalid argument: Input to DecodeRaw has length 154587 that is not a multiple of 4, the size of float
	 [[Node: DecodeRaw = DecodeRaw[little_endian=true, out_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](ParseSingleExample/Squeeze_img_raw)]]
Traceback (most recent call last):
  File "S:\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1021, in _do_call
    return fn(*args)
  File "S:\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1003, in _run_fn
    status, run_metadata)
  File "S:\Python35\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "S:\Python35\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 469, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.OutOfRangeError: RandomShuffleQueue '_1_shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 4, current size 0)
	 [[Node: shuffle_batch = QueueDequeueMany[_class=["loc:@shuffle_batch/random_shuffle_queue"], component_types=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](shuffle_batch/random_shuffle_queue, shuffle_batch/n)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "W:/PlantClassification/visualize_data.py", line 39, in <module>
    val, l = sess.run([img_batch, label_batch])
  File "S:\Python35\lib\site-packages\tensorflow\python\client\session.py", line 766, in run
    run_metadata_ptr)
  File "S:\Python35\lib\site-packages\tensorflow\python\client\session.py", line 964, in _run
    feed_dict_string, options, run_metadata)
  File "S:\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1014, in _do_run
    target_list, options, run_metadata)
  File "S:\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1034, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.OutOfRangeError: RandomShuffleQueue '_1_shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 4, current size 0)
	 [[Node: shuffle_batch = QueueDequeueMany[_class=["loc:@shuffle_batch/random_shuffle_queue"], component_types=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](shuffle_batch/random_shuffle_queue, shuffle_batch/n)]]

Caused by op 'shuffle_batch', defined at:
  File "W:/PlantClassification/visualize_data.py", line 27, in <module>
    num_threads=4)
  File "S:\Python35\lib\site-packages\tensorflow\python\training\input.py", line 917, in shuffle_batch
    dequeued = queue.dequeue_many(batch_size, name=name)
  File "S:\Python35\lib\site-packages\tensorflow\python\ops\data_flow_ops.py", line 458, in dequeue_many
    self._queue_ref, n=n, component_types=self._dtypes, name=name)
  File "S:\Python35\lib\site-packages\tensorflow\python\ops\gen_data_flow_ops.py", line 1099, in _queue_dequeue_many
    timeout_ms=timeout_ms, name=name)
  File "S:\Python35\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 759, in apply_op
    op_def=op_def)
  File "S:\Python35\lib\site-packages\tensorflow\python\framework\ops.py", line 2240, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "S:\Python35\lib\site-packages\tensorflow\python\framework\ops.py", line 1128, in __init__
    self._traceback = _extract_stack()

OutOfRangeError (see above for traceback): RandomShuffleQueue '_1_shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 4, current size 0)
	 [[Node: shuffle_batch = QueueDequeueMany[_class=["loc:@shuffle_batch/random_shuffle_queue"], component_types=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](shuffle_batch/random_shuffle_queue, shuffle_batch/n)]]

Process finished with exit code 1

**Comment by zsdonghao** [comment]
What data are you going to read? How did you create these data?
I think this is the key part: 
```
W c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:975] Invalid argument: Input to DecodeRaw has length 154587 that is not a multiple of 4, the size of float
[[Node: DecodeRaw = DecodeRawlittle_endian=true, out_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]]
```

**Comment by zsdonghao** [comment]
Automatically closing due to lack of recent activity. Please reopen when additional information becomes available. Thanks!
