### ISSUE TITLE
 tutorial_translate.py raise Exception("no %s exist" % ckpt.model_checkpoint_path)

### ISSUE THREAD

**Issue by terryKing1992** [zsdonghao/tensorlayer#40]
Hi Guys, I have trained the translation model using `python tuaorial_translate.py`, then i want using my own words to test the model,so i switch the main_train() to main_decode(), but the python shell raise one exception; more information as follow:
first, the exception occurs at 391 lines of tutorial_translate.py `if ckpt and tf.gfile.Exists(ckpt.model_checkpoint_path)`；and the ckpt object is not null, ckpt.model_checkpoint_path value is 'wmt/model_translate_enfr.ckpt-10'; in fact, the directory does not have this file , i wonder why the pre-sentence `ckpt = tf.train.get_checkpoint_state(train_dir)`  return the error data, hope your help, please! thanks a lot

**Comment by zsdonghao** [comment]
It seem that you have problem with ckpt. 
Did you set a correct`train_dir`?
Alternatively, can you set `is_npz = True` then it will save the model into npz file instead of ckpt, it may help.

**Comment by terryKing1992** [comment]
yeah, my train_dir is  a relative file path `wmt`, isn't it true? i'll try to set `is_npz=True`, should i remove the generated data and train the translate model again?
