### ISSUE TITLE
How to concat a cnn model and a nn model

### ISSUE THREAD

**Issue by tobymu** [zsdonghao/tensorlayer#41]
I'm trying to concat a cnn model and a nn model together. After concat them, I want to add a full-connected nn network.It always says error when I concat them. I don't know why.
TypeError: cannot convert dictionary update sequence element #0 to a sequence

**Comment by zsdonghao** [comment]
The key function of [ConcatLayer](http://tensorlayer.readthedocs.io/en/latest/modules/layers.html#concat-layer) is `tf.concat`, to concat the outputs of CNN and FC together, you will need to flatten the CNN output to `[batch_size, n_feature1]` then concat it to the FC output of `[batch_size, n_feature2]` with concat_dim =1 (default is 1).  Please have a look at the example in [RTD](http://tensorlayer.readthedocs.io/en/latest/modules/layers.html#concat-layer).

However, `TypeError: cannot convert dictionary update sequence element #0 to a sequence` doesn't seem to be a TensorFlow error. Your code format is broken, cannot be read.

**Comment by tobymu** [comment]
`import numpy as np
import tensorflow as tf
import tensorlayer as tl
from tensorlayer.layers import set_keep
import time


def nn_mix_cnn_model(X_train,y_train,X_val,y_val,X_test,y_test):    
    X_train, y_train, X_val, y_val, X_test, y_test = tl.files.load_mnist_dataset(shape=(-1,784))
    X_train = np.asarray(X_train, dtype=np.float32)
    y_train = np.asarray(y_train, dtype=np.int64)
    X_val = np.asarray(X_val, dtype=np.float32)
    y_val = np.asarray(y_val, dtype=np.int64)
    X_test = np.asarray(X_test, dtype=np.float32)
    y_test = np.asarray(y_test, dtype=np.int64)

    print('X_train.shape', X_train.shape)
    print('y_train.shape', y_train.shape)
    print('X_val.shape', X_val.shape)
    print('y_val.shape', y_val.shape)
    print('X_test.shape', X_test.shape)
    print('y_test.shape', y_test.shape)
    print('X %s   y %s' % (X_test.dtype, y_test.dtype))

    sess = tf.InteractiveSession()

    # placeholder
    x = tf.placeholder(tf.float32, shape=[None, 784], name='x')
    y_ = tf.placeholder(tf.int64, shape=[None, ], name='y_')

    print("Building Network")
    
    
    """ nn model """
    net_1 = tl.layers.InputLayer(x, name='nn_input_layer')
    net_1 = tl.layers.DropoutLayer(net_1, keep=0.8, name='nn_drop1')
    net_1 = tl.layers.DenseLayer(net_1, n_units=800, act = tf.nn.relu, name='nn_relu1')
    net_1 = tl.layers.DropoutLayer(net_1, keep=0.5, name='nn_drop2')
    net_1 = tl.layers.DenseLayer(net_1, n_units=800, act = tf.nn.relu, name='nn_relu2')
    #net_1 = tl.layers.DropoutLayer(net_1, keep=0.5, name='nn_drop3')
    """    
    net_1 = tl.layers.DenseLayer(net_1, n_units=10,
                                 act = tf.identity,
                                 name='nn_output_layer')
    """

    """ cnn model """
    x_image = tf.reshape(x, shape=[-1,28,28,1])
    net_2 = tl.layers.InputLayer(x_image, name='cnn_input_layer')
    net_2 = tl.layers.Conv2dLayer(net_2,
                        act = tf.nn.relu,
                        shape = [5, 5, 1, 32],  # 32 features for each 5x5 patch
                        strides=[1, 1, 1, 1],
                        padding='SAME',
                        name ='cnn_layer1')     # output: (?, 28, 28, 32)
    net_2 = tl.layers.PoolLayer(net_2,
                        ksize=[1, 2, 2, 1],
                        strides=[1, 2, 2, 1],
                        padding='SAME',
                        pool = tf.nn.max_pool,
                        name ='cnn_pool_layer1',)   # output: (?, 14, 14, 32)
    net_2 = tl.layers.Conv2dLayer(net_2,
                        act = tf.nn.relu,
                        shape = [5, 5, 32, 64], # 64 features for each 5x5 patch
                        strides=[1, 1, 1, 1],
                        padding='SAME',
                        name ='cnn_layer2')     # output: (?, 14, 14, 64)
    net_2 = tl.layers.PoolLayer(net_2,
                        ksize=[1, 2, 2, 1],
                        strides=[1, 2, 2, 1],
                        padding='SAME',
                        pool = tf.nn.max_pool,
                        name ='cnn_pool_layer2',)   # output: (?, 7, 7, 64)
    net_2 = tl.layers.FlattenLayer(net_2, name='cnn_flatten_layer')   # output: (?, 3136)
    net_2 = tl.layers.DropoutLayer(net_2, keep=0.5, name='cnn_drop1') # output: (?, 3136)
    net_2 = tl.layers.DenseLayer(net_2, n_units=256, act = tf.nn.relu, name='cnn_relu1')   # output: (?, 256)
    #net_2 = tl.layers.DropoutLayer(net_2, keep=0.5, name='drop2') # output: (?, 256)
    """    
    net_2 = tl.layers.DenseLayer(net_2, n_units=10,
                                    act = tf.identity,
                                    name='output_layer')    # output: (?, 10)
    """
    
    
    """ mix model """         
    network = tl.layers.ConcatLayer(layer = [net_1, net_2], name ='concat_layer')
    network = tl.layers.FlattenLayer(network, name='mix_flatten_layer')   # output: (?, 3136)
    network = tl.layers.DropoutLayer(network, keep=0.5, name='mix_drop1') # output: (?, 800+256)
    network = tl.layers.DenseLayer(network, n_units=1000, act = tf.nn.relu, name='mix_relu1')   # output: (?, 1056)
    network = tl.layers.DropoutLayer(network, keep=0.5, name='mix_drop2') # output: (?, 1056)
    network = tl.layers.DenseLayer(network, n_units=10, act = tf.identity, name='output_layer')    # output: (?, 10)
    
    y = network.outputs
    y_op = tf.argmax(tf.nn.softmax(y), 1)
    cost = tf.reduce_mean(tf.nn.sparse_softmax_cross_entropy_with_logits(y, y_))
    params = network.all_params
    
    # train
    n_epoch = 100
    batch_size = 128
    learning_rate = 0.0001
    print_freq = 5
    train_op = tf.train.AdamOptimizer(learning_rate, beta1=0.9, beta2=0.999,
                                epsilon=1e-08, use_locking=False).minimize(cost)

    sess.run(tf.initialize_all_variables()) # initialize all variables

    network.print_params()
    network.print_layers()

    print('   learning_rate: %f' % learning_rate)
    print('   batch_size: %d' % batch_size)
    

if __name__ == '__main__':
    #sess = tf.InteractiveSession()
    X_train, y_train, X_val, y_val, X_test, y_test = tl.files.load_mnist_dataset(shape=(-1,784))
    nn_mix_cnn_model(X_train,y_train,X_val,y_val,X_test,y_test)`

**Comment by tobymu** [comment]
Thanks for your comment.
But I don't think the key point is the wrong use of function ConcatLayer.

If I do nothing after concat, just directly output, the programme runs well.
If I do any operation, such as add a denselayer or a droplayer, it will cause the Error `TypeError: cannot convert dictionary update sequence element #0 to a sequence`

I have re-edited the code as below:

`import numpy as np
import tensorflow as tf
import tensorlayer as tl
from tensorlayer.layers import set_keep
import time

X_train, y_train, X_val, y_val, X_test, y_test = tl.files.load_mnist_dataset(shape=(-1,784))
X_train = np.asarray(X_train, dtype=np.float32)
y_train = np.asarray(y_train, dtype=np.int64)
X_val = np.asarray(X_val, dtype=np.float32)
y_val = np.asarray(y_val, dtype=np.int64)
X_test = np.asarray(X_test, dtype=np.float32)
y_test = np.asarray(y_test, dtype=np.int64)
    
sess = tf.InteractiveSession()

# placeholder
x = tf.placeholder(tf.float32, shape=[None, 784], name='x')
y_ = tf.placeholder(tf.int64, shape=[None, ], name='y_')

print("Building Network")
        
""" nn model """
net_1 = tl.layers.InputLayer(x, name='nn_input_layer')
net_1 = tl.layers.DropoutLayer(net_1, keep=0.8, name='nn_drop1')
net_1 = tl.layers.DenseLayer(net_1, n_units=800, act = tf.nn.relu, name='nn_relu1')
net_1 = tl.layers.DropoutLayer(net_1, keep=0.5, name='nn_drop2')
net_1 = tl.layers.DenseLayer(net_1, n_units=800, act = tf.nn.relu, name='nn_relu2')
#net_1 = tl.layers.DropoutLayer(net_1, keep=0.5, name='nn_drop3')

""" cnn model """
x_image = tf.reshape(x, shape=[-1,28,28,1])
net_2 = tl.layers.InputLayer(x_image, name='cnn_input_layer')
net_2 = tl.layers.Conv2dLayer(net_2,
                        act = tf.nn.relu,
                        shape = [5, 5, 1, 32],  # 32 features for each 5x5 patch
                        strides=[1, 1, 1, 1],
                        padding='SAME',
                        name ='cnn_layer1')     # output: (?, 28, 28, 32)
net_2 = tl.layers.PoolLayer(net_2,
                        ksize=[1, 2, 2, 1],
                        strides=[1, 2, 2, 1],
                        padding='SAME',
                        pool = tf.nn.max_pool,
                        name ='cnn_pool_layer1',)   # output: (?, 14, 14, 32)
net_2 = tl.layers.Conv2dLayer(net_2,
                        act = tf.nn.relu,
                        shape = [5, 5, 32, 64], # 64 features for each 5x5 patch
                        strides=[1, 1, 1, 1],
                        padding='SAME',
                        name ='cnn_layer2')     # output: (?, 14, 14, 64)
net_2 = tl.layers.PoolLayer(net_2,
                        ksize=[1, 2, 2, 1],
                        strides=[1, 2, 2, 1],
                        padding='SAME',
                        pool = tf.nn.max_pool,
                        name ='cnn_pool_layer2',)   # output: (?, 7, 7, 64)
net_2 = tl.layers.FlattenLayer(net_2, name='cnn_flatten_layer')   # output: (?, 3136)
net_2 = tl.layers.DropoutLayer(net_2, keep=0.5, name='cnn_drop1') # output: (?, 3136)
net_2 = tl.layers.DenseLayer(net_2, n_units=256, act = tf.nn.relu, name='cnn_relu1')   # output: (?, 256)
#net_2 = tl.layers.DropoutLayer(net_2, keep=0.5, name='drop2') # output: (?, 256)

""" mix model """         
network = tl.layers.ConcatLayer(layer = [net_1, net_2], name ='concat_layer')
network = tl.layers.DropoutLayer(network, keep=0.5, name='mix_drop1') # output: (?, 800+256)
network = tl.layers.DenseLayer(network, n_units=1000, act = tf.nn.relu, name='mix_relu1')   # output: (?, 1056)
network = tl.layers.DropoutLayer(network, keep=0.5, name='mix_drop2') # output: (?, 1056)
network = tl.layers.DenseLayer(network, n_units=10, act = tf.identity, name='output_layer')    # output: (?, 10)
    
y = network.outputs
y_op = tf.argmax(tf.nn.softmax(y), 1)
cost = tf.reduce_mean(tf.nn.sparse_softmax_cross_entropy_with_logits(y, y_))
params = network.all_params
    
# train
n_epoch = 100
batch_size = 128
learning_rate = 0.0001
print_freq = 5
train_op = tf.train.AdamOptimizer(learning_rate, beta1=0.9, beta2=0.999,
                                epsilon=1e-08, use_locking=False).minimize(cost)

sess.run(tf.initialize_all_variables()) # initialize all variables

network.print_params()
network.print_layers()

print('   learning_rate: %f' % learning_rate)
print('   batch_size: %d' % batch_size)`

**Comment by zsdonghao** [comment]
@tobymu Hi, I ran you code and fixed the bug in ConcatLayer, see [last commit](https://github.com/zsdonghao/tensorlayer/commit/400d717ca2e6e3ee4d9ba2e5e14754d859882310).

Please reinstall TL from git, and run your script again, it should work.

Thanks

**Comment by tobymu** [comment]
@zsdonghao Thanks for your work!
Yeah, I've tried again, and it does work now!

**Comment by zsdonghao** [comment]
Fixed
