### ISSUE TITLE
AttributeError: 'module' object has no attribute 'rnn_cell'

### ISSUE THREAD

**Issue by Bishopxu** [zsdonghao/tensorlayer#48]
when  import tensorlayer:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorlayer/__init__.py", line 19, in <module>
    from . import layers
  File "/usr/local/lib/python2.7/dist-packages/tensorlayer/layers.py", line 1939, in <module>
    class RNNLayer(Layer):
  File "/usr/local/lib/python2.7/dist-packages/tensorlayer/layers.py", line 2093, in RNNLayer
    cell_fn = tf.nn.rnn_cell.BasicRNNCell,
AttributeError: 'module' object has no attribute 'rnn_cell'

python2.7,  CUDA8.0, cudnn5.1, tensorflow_GPU0.12.0, ubuntu16.04
My tensorflow runs successful, how to solve this problem?

**Comment by wagamamaz** [comment]
@Bishopxu can you try this:
```python
import tensorflow as tf
print(tf.nn.rnn_cell.BasicRNNCell)
```
It is work?

**Comment by Bishopxu** [comment]
>>> import tensorflow as tf
I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcurand.so.8.0 locally
W tensorflow/core/platform/cpu_feature_guard.cc:95] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:95] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:95] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:95] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
>>> print(tf.nn.rnn_cell.BasicRNNCell)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'rnn_cell'

**Comment by Bishopxu** [comment]
`>>> import tensorflow as tf
I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcurand.so.8.0 locally
W tensorflow/core/platform/cpu_feature_guard.cc:95] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:95] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:95] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:95] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
>>> print(tf.nn.rnn_cell.BasicRNNCell)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'rnn_cell'
`

**Comment by Bishopxu** [comment]
>>> import tensorflow as tf
I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcurand.so.8.0 locally
W tensorflow/core/platform/cpu_feature_guard.cc:95] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:95] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:95] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:95] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
>>> print(tf.nn.rnn_cell.BasicRNNCell)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'rnn_cell'
>>>

**Comment by Bishopxu** [comment]
Is this a problem with tensorflow installation? I have seen a similar question in this:https://github.com/tensorflow/skflow/issues/98

**Comment by Bishopxu** [comment]
I feel so sorry for not replying to you in time. This error has been solved by install the tensorflow 0.12.1.
Thank you for your great help!

**Comment by Noahsark** [comment]
I also met the problem and update to 0.12.1 does not work for me! Any ideas? 
Thanks!

**Comment by wagamamaz** [comment]
@Noahsark what is your error?

**Comment by Noahsark** [comment]
@wagamamaz same problem with those above: AttributeError: 'module' object has no attribute 'rnn_cell'

**Comment by Noahsark** [comment]
I think the problem may caused by bazel. There are 2 remain errors when compiling the source code on my machine:
**arning: ignoring LD_PRELOAD in environment.
ERROR: /home/renli/.cache/bazel/_bazel_renli/fa58df3c1dc3dbbfc82c89fb001121cc/external/local_config_cuda/crosstool/BUILD:4:1: Traceback (most recent call last):
        File "/home/renli/.cache/bazel/_bazel_renli/fa58df3c1dc3dbbfc82c89fb001121cc/external/local_config_cuda/crosstool/BUILD", line 4
                error_gpu_disabled()
        File "/home/renli/.cache/bazel/_bazel_renli/fa58df3c1dc3dbbfc82c89fb001121cc/external/local_config_cuda/crosstool/error_gpu_disabled.bzl", line 3, in error_gpu_disabled
                fail("ERROR: Building with --config=c...")
ERROR: Building with --config=cuda but TensorFlow is not configured to build with GPU support. Please re-run ./configure and enter 'Y' at the prompt to build with GPU support.
ERROR: no such target '@local_config_cuda//crosstool:toolchain': target 'toolchain' not declared in package 'crosstool' defined by /home/renli/.cache/bazel/_bazel_renli/fa58df3c1dc3dbbfc82c89fb001121cc/external/local_config_cuda/crosstool/BUILD.**

@wagamamaz FYI

**Comment by Noahsark** [comment]
Here I found the changes may cause this problem. 
[](https://github.com/tensorflow/tensorflow/commit/b8101a2b0a7ff1b96999c8e7ad213d1f36b4a4ab)

The rnn_cell was moved to tf.contrib instead after Dec 5. Why did the document not mention this change? 

@wagamamaz @Bishopxu

**Comment by zsdonghao** [comment]
@Noahsark there is not `tf.contrib.rnn.LSTMCell` in TensorLayer , we only use `tf.nn.rnn_cell.LSTMCell`, I believe it is not caused by TensorLayer

**Comment by Noahsark** [comment]
@zsdonghao 
I am sorry that I just realized this post is under the response of TensorLayer not TensorFlow.

**Comment by aronayne** [comment]
@Noahsark did you resolve your issue, can share steps if resolved ? I'm receiving same on tensorflow version 0.12.head and Python 2.7.6 : 

  File "/notebooks/models/tutorials/rnn/translate/seq2seq_model.py", line 117, in __init__
    single_cell = tf.nn.rnn_cell.GRUCell(size)
AttributeError: 'module' object has no attribute 'rnn_cell'

Received this while running translate model : https://github.com/tensorflow/models/tree/master/tutorials/rnn/translate
