### ISSUE TITLE
Conv1d shape and stride problem

### ISSUE THREAD

**Issue by hongzimao** [zsdonghao/tensorlayer#50]
I am passing a batch of 1D vector as input and need a convolution 1D layer in the middle. However, when I do 
```
tl.layers.Conv1dLayer(in_net, act=tf.nn.relu, shape=[5, 1, 50], strides=[1, 1, 1], padding='SAME', name='cnn_0')
```
where `in_net` is the inputlayer. 

But I got an error message of 
```
TypeError: Expected int for argument 'strides' not [1, 1, 1].
```

If I change to `stride=1`, I got error
```
ValueError: Shape must be rank 4 but is rank 3
```

Can someone help me out? Thanks.

**Comment by zsdonghao** [comment]
Please check https://www.tensorflow.org/versions/master/api_docs/python/nn/convolution#conv1d

The strides should be an integer, and the input shape should be 3D, i.e. [batch_size, n_width, n_channel]

**Comment by zsdonghao** [comment]
i think the problem have been solved?
