### ISSUE TITLE
Unpooling Layers linked with Max Pooling Layers

### ISSUE THREAD

**Issue by JoelKronander** [zsdonghao/tensorlayer#54]
I am looking to implement "Unpooling" layers that upsamples an image and "undoes" a corresponding max-pooling layer. For example, used in SegNet type architecures.

Is there some good way of implementing this in TensorLayer?

**Comment by zsdonghao** [comment]
@JoelKronander I think `UpSampling2dLayer` or `DeConv2d` should work in your case.

**Comment by JoelKronander** [comment]
Sorry for being a bit vague. 
UpSammpling2dLayer or Deconv2D is not what I am looking for. 
I am looking for an "Unpooling" layer, explicitly linked to the pooling indicies in an earlier max-pooling layer, for example used in encoder-decoder type models. The "unpooling" upsamples the feature map by coping the input to the location resulting from the max pooling operation and fills in zeros for the other values in the upsampled feature map.
See e.g. the Segnet paper https://arxiv.org/abs/1511.00561 on top left of page 6 for an illustration. This "Unpooling" layer thus needs to access the stored max pooling indicies in a corresponding max_pooling layer.

**Comment by zsdonghao** [comment]
@JoelKronander from the top left of page 6 , the author said: `Deconvolution for upsampling` , so as my understand it should be `DeConv2d`

**Comment by JoelKronander** [comment]
No it is not the same as a regular DeConv2DLayer, which is not using the indicies from a particular max pooling layer. Often in Sementation Networks the Unpooling layer is followed by convolutions, but it is not the same as a single DeConv2DLayer.
A more formal description is available in the torch documentation:
https://github.com/torch/nn/blob/master/doc/convolution.md#spatialmaxunpooling

**Comment by zsdonghao** [comment]
@JoelKronander as you already implemented that part and push to the master, i close this issues now ~

**Comment by FangliangBai** [comment]
Sorry, I didn't catch what @zsdonghao said here. He said this has been implemented in Tensorlayer but I couldn't find it in the document. Could either of you provide a link please? Much appreciated.
