### ISSUE TITLE
How to get layer (output) by name?

### ISSUE THREAD

**Issue by JindongJiang** [zsdonghao/tensorlayer#58]
Some deep learning task, such as SSD and neural-style may need to extract previous layers. While it seems that we have to explicitly store those certain layers in v1.3.0, instead of getting it by name like `network[conv5_3]`. But I found that we have a self.all_layers Attribute in Layer, update in a new layer like:

```python
self.all_layers = list(layer.all_layers)
...
self.all_layers.extend( [self.outputs] )
```
should we simply turn this list into dict: `self.all_layers['conv5_3'] = self.output` ? Then we can get layer output by name `network.all_layers[conv5_3]`.
Or we already have another way to access every output?

**Comment by zsdonghao** [comment]
@JindongJiang Good idea, indeed.

I think we can create 2 functions for `Layer` class : `network.get_layers_by_name("conv2")` and `network.get_params_by_name("W")`.

`network.get_params_by_name("W")` should be similar with `tl.layer. get_variables_with_name()` as follow:
```
def get_variables_with_name(name, train_only=True, printable=False):
    """Get variable list by a given name scope.

    Examples
    ---------
    >>> dense_vars = get_variable_with_name('dense', True, True)
    """
    print("  Get variables with %s" % name)
    t_vars = tf.trainable_variables() if train_only else tf.all_variables()
    d_vars = [var for var in t_vars if name in var.name]
    if printable:
        for idx, v in enumerate(d_vars):
            print("  got {:3}: {:15}   {}".format(idx, v.name, str(v.get_shape())))
    return d_vars
```

You can try this code by adding it to `Layer`:
```
def get_params_by_name(self, name, printable=False):
    print("  Get params in a network with %s" % name)
    t_vars = self.all_params
    d_vars = [var for var in t_vars if name in var.name]
    if printable:
        for idx, v in enumerate(d_vars):
            print("  got {:3}: {:15}   {}".format(idx, v.name, str(v.get_shape())))
    return d_vars
```

**Comment by JindongJiang** [comment]
@zsdonghao Thx. And w.r.t network.get_layers_by_name maybe :
```python
self.all_layers = layer.all_layers
...
self.all_layers[name] = self.output
```
and:
```python
def get_layers_by_name(self, name):
    print("  Get layers in a network with %s" % name)
    d_layers = self.all_layers.get(name, None)
    if d_layers is None:
        print(" %s not implemented ".format(name))
    return d_layers
```
Could work ?

**Comment by zsdonghao** [comment]
I think it should work, but it that possible don't add new code into every layers?

**Comment by zsdonghao** [comment]
@JindongJiang [tl.layers.get_layers_with_name](http://tensorlayer.readthedocs.io/en/latest/modules/layers.html#get-layers-with-name) is now in the master version
