### ISSUE TITLE
Feature Request/Discussion: Testing suite for Pull Requests

### ISSUE THREAD

**Issue by JoelKronander** [zsdonghao/tensorlayer#61]
To make it easier to contribute code it would be great if there was a set of existing tests collected in one place that could be run on committed code/Pull Requests. 
Maybe the absolute best would be some form of TravisCI as for TFLearn?

See e.g. [Keras tests](https://github.com/fchollet/keras/blob/master/CONTRIBUTING.md) 
or [TFLearn tests](https://github.com/tflearn/tflearn/tree/master/tests)

**Comment by zsdonghao** [comment]
@JoelKronander yeah, we should do that ..

**Comment by JoelKronander** [comment]
;) What kind of approach would be best?
using pytest built in unittests?

**Comment by zsdonghao** [comment]
I think contributors may like to use built-in library, and just simply excute a .py program ~

**Comment by zsdonghao** [comment]
Hi all, a easy way to test before push request is:

Run this scripts :tutorial_mnist_simple.py, tutorial_cifar10_tfrecord.py and tutorial_ptb_lstm_state_is_tuple.py under python2.7, 3.4, 3.5

**Comment by zsdonghao** [comment]
hi, feel free to reopen this discussion.
