### ISSUE TITLE
module 'tensorlayer' has no attribute 'files'

### ISSUE THREAD

**Issue by gdyxml2000** [zsdonghao/tensorlayer#62]
when i run "tutorial_mnist_simple.py" in eclipse ,i have get a error message:

X_train, y_train, X_val, y_val, X_test, y_test =tl.files.load_mnist_dataset(shape=(-1,784))
AttributeError: module 'tensorlayer' has no attribute 'files'

when i run   "tutorial_mnist_simple.py" in Pycharm, it will be ok.
but, my eclipse run tensorflow simples ,has no errors!

**Comment by JoelKronander** [comment]
Are sure you have correctly installed tensorlayer and that your PYTHONPATH enviroment variable is set correctly?

comapre the PYTHONPATH in eclipse and Pycharm for example.

**Comment by gdyxml2000** [comment]
Set the environment variable PYTHONPATH in eclipse RunConfiguration, this problem is solved. thanks!

**Comment by zsdonghao** [comment]
Great!
