### ISSUE TITLE
resnet example

### ISSUE THREAD

**Issue by xjtuljy** [zsdonghao/tensorlayer#63]
Thank you for providing such a powerful but user-friendly wrapper. Is there any example for resnet in which the network cannot be constructed by simply stacking layer by layer, by using tl.layer?

**Comment by zsdonghao** [comment]
@xjtuljy You can connect TF-Slim into TensorLayer, as TF-Slim have pre-trained resnet, inception , vgg models .. see `tutorial_inceptionV3_tfslim.py` in example folder.

Besides, here is a [resnet example](https://github.com/ritchieng/wideresnet-tensorlayer) implemented by @ritchieng

**Comment by xjtuljy** [comment]
Thanks! @ritchieng 's code is quite helpful!
