### ISSUE TITLE
Should load datasets function in tl.files receive path argument to specify the data path?

### ISSUE THREAD

**Issue by boscotsang** [zsdonghao/tensorlayer#64]
Now the load datasets functions in tl.files store the data files in current work directory and have no way to customize the path. I wonder if I can add path parameter to specify the data path. If no specification path, it is store in ~/.tensorlayer/datasets/. If you think so, I may do this work.

**Comment by zsdonghao** [comment]
@boscotsang good idea, go ahead. please make sure previous codes can run normally.

Thank you ~~

**Comment by JoelKronander** [comment]
Can you combine this with PR 60 Please? Cleaner code that way imho

**Comment by boscotsang** [comment]
@JoelKronander I've submited a pr before combine with PR 60. Would you do this?

**Comment by JoelKronander** [comment]
Sure! Will base it on your PR.
