### ISSUE TITLE
Bug in tutorial_cifar10_tfrecords.py

### ISSUE THREAD

**Issue by JoelKronander** [zsdonghao/tensorlayer#69]
There seems to be a bug in the examples/tutorials_cifar10_tfrecords.py

Using tensorflow 0.12.1 I get the following error:
  File "tutorial_cifar10_tfrecord.py", line 116, in read_and_decode
    img = tf.image.per_image_whitening(img)
AttributeError: 'module' object has no attribute 'per_image_whitening'
[deepmind@deepmind tensorlayer]$

**Comment by zsdonghao** [comment]
@JoelKronander  Oh... TF 0.12 removes `tf.image.per_image_whitening()`  ..
It works well under TF 0.11
