### ISSUE TITLE
LookupError: No gradient defined for operation 'gradients_1/continous_shared/continous_pool1_grad/MaxPoolGrad' (op type: MaxPoolGrad)

### ISSUE THREAD

**Issue by jjkke88** [zsdonghao/tensorlayer#71]
when I use tf.gradient to calculate gradient ` grads = tf.gradients(loss, var_list)`, `var_list=tf.trainable_variables()`, the error `LookupError: No gradient defined for operation 'gradients_1/continous_shared/continous_pool1_grad/MaxPoolGrad' (op type: MaxPoolGrad)` shows.

**Comment by zsdonghao** [comment]
what is your var_list?
you should do:
grads = tf.gradients(loss, var_list=`<list of params>`)

**Comment by wagamamaz** [comment]
@jjkke88 can't help without your code

**Comment by zsdonghao** [comment]
Automatically closing due to lack of recent activity. Please reopen when additional information becomes available. Thanks!
