### ISSUE TITLE
tensorlayer.visualize.W : error "total size of new array must be unchanged"

### ISSUE THREAD

**Issue by haigu12** [zsdonghao/tensorlayer#8]
looks like tensorlayer.visualize.W() always throws an error "total size of new array must be unchanged".

perhaps it is because of the line " feature = W[:,count-1] / np.sqrt( (W[:,count-1]**2).sum()) "
where if count==1, then it will be an empty list.

**Comment by wagamamaz** [comment]
@haigu12 can you show your code, when you got this error ?
How is your weight matrix look like ?

**Comment by haigu12** [comment]
@wagamamaz 
the network code is:

'''define placeholders'''
x = tf.placeholder(tf.float32, shape=[None, 1], name='x')
y_= tf.placeholder(tf.float32, shape=[None, 1], name='y_')

'''define the network'''
network = tl.layers.InputLayer(x, name='input_layer')
network = tl.layers.DenseLayer(network, n_units=16, act = tf.nn.relu, name='relu1')
network = tl.layers.DenseLayer(network, n_units=4, act = tf.nn.relu, name='relu2')
network = tl.layers.DenseLayer(network, n_units=1, act = tf.nn.relu, name='result')

and after training, 
>>> network.all_params[0].eval()
array([[-0.12620708, -0.13378434,  0.05406925, -0.06829847,  0.12863488,
        -0.0354087 , -0.01825967,  0.06813091, -0.05230081, -0.09361359,
        -0.08705429,  0.08989979, -0.17979668,  0.01737362,  0.11124372,
         0.04816928]], dtype=float32)

**Comment by zsdonghao** [comment]
Hi, your shape is incorrect, and why you use DensLayer when X only have one feature?
Check you model pls.

**Comment by haigu12** [comment]
Ah, I see, the shape should be [1,1].
It's only a test program, and I was trying to make things simple.
