### ISSUE TITLE
Does tensorlayer support distributed training?

### ISSUE THREAD

**Issue by boscotsang** [zsdonghao/tensorlayer#82]
Training model distributely with replicated models is critical for large scale deep learning training. I'm wondering whether tensorlayer support it and whether there is any tutorials for it?

**Comment by boscotsang** [comment]
Is there any way to specify the weights variable to PS server while the matmul to worker server in a layer? Thank you.

**Comment by wagamamaz** [comment]
@boscotsang this link may help https://www.tensorflow.org/deploy/distributed

**Comment by zsdonghao** [comment]
i think the problem have been solved?

**Comment by boscotsang** [comment]
Yeah, thank you
