### ISSUE TITLE
how to use tensorlayer birnn split_input ?

### ISSUE THREAD

**Issue by guoying1030** [zsdonghao/tensorlayer#83]
I would like to use tensorlayer realize neon inside the function of Birnn, neon inside the BiRnn you can set split_input, the meaning of this parameter is: split_inputs (bool): to expect the input coming from the same source of separate Sources, but tensorlayer which birnn inside, I do not know how to set up this parameter? ?? This parameter from the code inside the neon see, assuming that the input is [32,1000,2304], respectively, on behalf of the [batch_size, n_step, hidden_size], then how split_input parameter is set to true, the function is running, [32,1000,1152] is used for forward propagation operations, and [32,1000,1152] is used for backward propagation operations. Then tensorlayer inside how to set up?

**Comment by wagamamaz** [comment]
it is hard to understand what you are trying to do.

**Comment by wagamamaz** [comment]
@guoying1030 https://github.com/zsdonghao/tensorlayer/blob/master/example/tutorial_ptb_lstm_state_is_tuple.py

just simply change `tl.layers.RNNLayer` to `tl.layers.BiRNNLayer `, it automatically do bidirectional staff for you.
