### ISSUE TITLE
the ReconLayer.pretrain() function hard coded visualize.W shape to be 28*28 

### ISSUE THREAD

**Issue by haigu12** [zsdonghao/tensorlayer#9]
The ReconLayer.pretrain() function has hard coded visualize.W() shape to be 28*28, so if we change the training data shape it will crash.

This shape should be drawn from the input data.

**Comment by zsdonghao** [comment]
the default visualization of ReconLayer is for MNIST dataset, if you want to modify the pretrain function, please have a look at the following tutorial on our website:

http://tensorlayer.readthedocs.io/en/latest/modules/layers.html#modifying-pre-train-behaviour

However, if you change the training data shape it will **NOT** crash, as **pretrain** function uses **try** as follow.
```
if save:
      try:
            visualize.W(self.train_params[0].eval(), second=10, saveable=True, shape=[28,28], name=save_name+str(epoch+1), fig_idx=2012)
            files.save_npz([self.all_params[0]] , name=save_name+str(epoch+1)+'.npz')
      except:
            raise Exception("You should change visualize.W(), if you want to save the feature images for different dataset")
```

We primarily use github issues to track bugs and installation issues. This is a question better suited for StackOverflow. Please ask it there and tag it with the ``tensorlayer`` tag. Thanks!
