### ISSUE TITLE
When you are planning to release update for TF 1.0 ?

### ISSUE THREAD

**Issue by ruzrobert** [zsdonghao/tensorlayer#92]
Hello!
I am user of TensorFlow r1.0-rc2, but looks like Tensorlayer is developing for 12.1 right now.
When you are planning to update TL for TF 1.0 ?

Thanks!

Robert

**Comment by wagamamaz** [comment]
for TF 1.0 please update to master version `pip install git+https://github.com/zsdonghao/tensorlayer.git`

**Comment by zsdonghao** [comment]
TL supports TF 1.0
