### ISSUE TITLE
tutorial_mnist.py show:  'np' is not defined

### ISSUE THREAD

**Issue by anxingle** [zsdonghao/tensorlayer#95]
My tensorflow is  1.0.0 and I just install tensorlayer a hour ago.  It `
    File **tutorial_mnist.py**, line 570, in <module>          
    sess = tf.InteractiveSession()             
    File **tutorial_mnist.py**, line 34, in main_test_layers       
    tl.files.load_mnist_dataset(shape=(-1,784))       
    NameError: name **np** is not defined     
                 `
Works well when I run tutorial_mnist_simple.py.  I install numpy  correctly  and can use it.

**Comment by wagamamaz** [comment]
please install numpy then .

**Comment by anxingle** [comment]
@wagamamaz   Please don't close so soon. U don't investigate it deeply. As far as I know, it is the encoding problem of the file and not is my configure problem.

**Comment by anxingle** [comment]
I  rewrite it (in vim ) and solve the problem.

**Comment by littlejiafan** [comment]
I meet the same problem, so how did you rewrite it in vim in detail, thanks a lot 啊
